export default[
  {
    name: 'Marathon',
    value: 'Gestalt::Configuration::Provider::CaaS::DCOS',
    type: 'container',
    url: true,
    auth: true,
    networking: true,
    extraConfig: true,
    uploadConfig: false,
  },
  {
    name: 'Kubernetes',
    value: 'Gestalt::Configuration::Provider::CaaS::Kubernetes',
    type: 'container',
    url: false,
    auth: false,
    networking: false,
    extraConfig: false,
    uploadConfig: true,
  },
  {
    name: 'Kong',
    value: 'Gestalt::Configuration::Provider::ApiGateway',
    type: 'apigateway',
    url: true,
    auth: true,
    networking: false,
    extraConfig: true,
    uploadConfig: false,
  },
];
