export default [
  {
    name: 'Mesosphere DC/OS',
    value: 'Gestalt::Configuration::Provider::CaaS::DCOS',
    type: 'DCOS',
    DCOSConfig: true,
    DCOSSecurity: true,
    networking: true,
    extraConfig: true,
    uploadConfig: false,
    allowContainer: false,
    externalProtocol: true,
    allowEnvVariables: true,
    DCOSEnterprise: true,
  },
  {
    name: 'Kubernetes',
    value: 'Gestalt::Configuration::Provider::CaaS::Kubernetes',
    type: 'KUBERNETES',
    networking: false,
    extraConfig: false,
    uploadConfig: true,
    allowContainer: false,
    externalProtocol: true,
    allowEnvVariables: true,
  },
  {
    name: 'Docker Swarm',
    value: 'Gestalt::Configuration::Provider::CaaS::Docker',
    type: 'DOCKER',
    networking: true,
    extraConfig: false,
    uploadConfig: false,
    allowContainer: false,
    externalProtocol: true,
    allowEnvVariables: true,
  },
  {
    name: 'APIGateway (Kong)',
    value: 'Gestalt::Configuration::Provider::Kong',
    type: 'KONG',
    networking: false,
    extraConfig: true,
    uploadConfig: false,
    allowContainer: true,
    externalProtocol: true,
    allowEnvVariables: true,
  },
  {
    name: 'GatewayManager',
    value: 'Gestalt::Configuration::Provider::GatewayManager',
    type: 'GATEWAYMANAGER',
    networking: false,
    extraConfig: true,
    uploadConfig: false,
    allowContainer: true,
    externalProtocol: false,
    allowEnvVariables: true,
  },
  {
    name: 'Security',
    value: 'Gestalt::Configuration::Provider::Security',
    type: 'SECURITY',
    networking: false,
    extraConfig: false,
    uploadConfig: false,
    allowContainer: false,
    externalProtocol: false,
    allowEnvVariables: true,
  },
  {
    name: 'PostgreSQL',
    value: 'Gestalt::Configuration::Provider::Data::PostgreSQL',
    type: 'DATA::POSTGRESQL',
    networking: false,
    extraConfig: false,
    uploadConfig: false,
    allowContainer: false,
    externalProtocol: false,
    allowEnvVariables: true,
  },
  {
    name: 'RabbitMQ',
    value: 'Gestalt::Configuration::Provider::Messaging::RabbitMQ',
    type: 'MESSAGING::RABBITMQ',
    networking: false,
    extraConfig: false,
    uploadConfig: false,
    allowContainer: true,
    externalProtocol: false,
    allowEnvVariables: true,
  },
  {
    name: 'Policy',
    value: 'Gestalt::Configuration::Provider::Policy',
    type: 'POLICY',
    networking: false,
    extraConfig: false,
    uploadConfig: false,
    allowContainer: true,
    externalProtocol: false,
    allowEnvVariables: true,
  },
  {
    name: 'Logging',
    value: 'Gestalt::Configuration::Provider::Logging',
    type: 'LOGGING',
    networking: false,
    extraConfig: false,
    uploadConfig: false,
    allowContainer: true,
    externalProtocol: false,
    allowEnvVariables: true,
  },
  {
    name: 'Lambda',
    value: 'Gestalt::Configuration::Provider::Lambda',
    type: 'LAMBDA',
    networking: false,
    extraConfig: false,
    uploadConfig: false,
    allowContainer: true,
    externalProtocol: false,
    allowEnvVariables: true,
  },
  {
    name: 'Lambda Executor NodeJS',
    value: 'Gestalt::Configuration::Provider::Lambda::Executor::NodeJS',
    type: 'LAMBDA::NODEJS',
    networking: false,
    extraConfig: false,
    uploadConfig: false,
    allowContainer: false,
    externalProtocol: false,
    allowEnvVariables: true,
  },
  {
    name: 'Lambda Executor Nashorn',
    value: 'Gestalt::Configuration::Provider::Lambda::Executor::Nashorn',
    type: 'LAMBDA::NASHORN',
    networking: false,
    extraConfig: false,
    uploadConfig: false,
    allowContainer: false,
    externalProtocol: false,
    allowEnvVariables: true,
  },
  {
    name: 'Lambda Executor Scala',
    value: 'Gestalt::Configuration::Provider::Lambda::Executor::Scala',
    type: 'LAMBDA::SCALA',
    networking: false,
    extraConfig: false,
    uploadConfig: false,
    allowContainer: false,
    externalProtocol: false,
    allowEnvVariables: true,
  },
  {
    name: 'Lambda Executor Java',
    value: 'Gestalt::Configuration::Provider::Lambda::Executor::Java',
    type: 'LAMBDA::JAVA',
    networking: false,
    extraConfig: false,
    uploadConfig: false,
    allowContainer: false,
    externalProtocol: false,
    allowEnvVariables: true,
  },
  {
    name: 'Lambda Executor Ruby',
    value: 'Gestalt::Configuration::Provider::Lambda::Executor::Ruby',
    type: 'LAMBDA::RUBY',
    networking: false,
    extraConfig: false,
    uploadConfig: false,
    allowContainer: false,
    externalProtocol: false,
    allowEnvVariables: true,
  },
  {
    name: 'Lambda Executor Python',
    value: 'Gestalt::Configuration::Provider::Lambda::Executor::Python',
    type: 'LAMBDA::PYTHON',
    networking: false,
    extraConfig: false,
    uploadConfig: false,
    allowContainer: false,
    externalProtocol: false,
    allowEnvVariables: true,
  },
  {
    name: 'Lambda Executor C#',
    value: 'Gestalt::Configuration::Provider::Lambda::Executor::CSharp',
    type: 'LAMBDA::CSHARP',
    networking: false,
    extraConfig: false,
    uploadConfig: false,
    allowContainer: false,
    externalProtocol: false,
    allowEnvVariables: true,
  },
  {
    name: 'Lambda Executor Go',
    value: 'Gestalt::Configuration::Provider::Lambda::Executor::GoLang',
    type: 'LAMBDA::GO',
    networking: false,
    extraConfig: false,
    uploadConfig: false,
    allowContainer: false,
    externalProtocol: false,
    allowEnvVariables: true,
  },
];
