export default[
  {
    name: 'DCOS',
    value: 'Gestalt::Configuration::Provider::CaaS::DCOS',
    type: 'DCOS',
    config: true,
    networking: true,
    extraConfig: true,
    uploadConfig: false,
    allowContainer: false,
  },
  {
    name: 'Kubernetes',
    value: 'Gestalt::Configuration::Provider::CaaS::Kubernetes',
    type: 'KUBERNETES',
    config: false,
    networking: false,
    extraConfig: false,
    uploadConfig: true,
    allowContainer: false,
  },
  {
    name: 'Kong',
    value: 'Gestalt::Configuration::Provider::Kong',
    type: 'KONG',
    config: false,
    networking: false,
    extraConfig: true,
    uploadConfig: false,
    allowContainer: true,
  },
  {
    name: 'GatewayManager',
    value: 'Gestalt::Configuration::Provider::GatewayManager',
    type: 'GATEWAYMANAGER',
    config: false,
    networking: false,
    extraConfig: true,
    uploadConfig: false,
    allowContainer: true,
  },
  {
    name: 'Security',
    value: 'Provider::Security',
    type: 'SECURITY',
    config: false,
    networking: false,
    extraConfig: false,
    uploadConfig: false,
    allowContainer: false,
  },
  {
    name: 'Database',
    value: 'Provider::Data::PostgreSQL',
    type: 'DATABASE::POSTGRESQL',
    config: false,
    networking: false,
    extraConfig: false,
    uploadConfig: false,
    allowContainer: false,
  },
  {
    name: 'Lambda',
    value: 'Gestalt::Configuration::Provider::Lambda',
    type: 'LAMBDA',
    config: false,
    networking: false,
    extraConfig: false,
    uploadConfig: false,
    allowContainer: false,
  },
  {
    name: 'Lambda Executor NodeJS',
    value: 'Provider::Lambda::Executor::NodeJS',
    type: 'LAMBDA::NODEJS',
    config: false,
    networking: false,
    extraConfig: false,
    uploadConfig: false,
    allowContainer: false,
  },
  {
    name: 'Lambda Executor Scala',
    value: 'Provider::Lambda::Executor::Scala',
    type: 'LAMBDA::SCALA',
    config: false,
    networking: false,
    extraConfig: false,
    uploadConfig: false,
    allowContainer: false,
  },
  {
    name: 'Lambda Executor Java',
    value: 'Provider::Lambda::Executor::Java',
    type: 'LAMBDA::JAVA',
    config: false,
    networking: false,
    extraConfig: false,
    uploadConfig: false,
    allowContainer: false,
  },
  {
    name: 'Lambda Executor Ruby',
    value: 'Provider::Lambda::Executor::Ruby',
    type: 'LAMBDA::RUBY',
    config: false,
    networking: false,
    extraConfig: false,
    uploadConfig: false,
    allowContainer: false,
  },
  {
    name: 'Lambda Executor Python',
    value: 'Provider::Lambda::Executor::Python',
    type: 'LAMBDA::PYTHON',
    config: false,
    networking: false,
    extraConfig: false,
    uploadConfig: false,
    allowContainer: false,
  },
  {
    name: 'Lambda Executor C#',
    value: 'Provider::Lambda::Executor::CSharp',
    type: 'LAMBDA::CHSHARP',
    config: false,
    networking: false,
    extraConfig: false,
    uploadConfig: false,
    allowContainer: false,
  },
  {
    name: 'Lambda Executor Go',
    value: 'Provider::Lambda::Executor::GoLang',
    type: 'LAMBDA::GO',
    config: false,
    networking: false,
    extraConfig: false,
    uploadConfig: false,
    allowContainer: false,
  },
];
