export const PREFIX = 'metaResource/';

// For initializing the STREAMSPEC create ui state
export const INIT_STREAMSPECCREATE_REQUEST = `${PREFIX}INIT_STREAMSPECCREATE_REQUEST`;
export const INIT_STREAMSPECCREATE_FULFILLED = `${PREFIX}INIT_STREAMSPECCREATE_FULFILLED`;
export const INIT_STREAMSPECCREATE_REJECTED = `${PREFIX}INIT_STREAMSPECCREATE_REJECTED`;
export const INIT_STREAMSPECCREATE_CANCELLED = `${PREFIX}INIT_STREAMSPECCREATE_CANCELLED`;

// For initializing the STREAMSPEC edit ui state
export const INIT_STREAMSPECEDIT_REQUEST = `${PREFIX}INIT_STREAMSPECEDIT_REQUEST`;
export const INIT_STREAMSPECEDIT_FULFILLED = `${PREFIX}INIT_STREAMSPECEDIT_FULFILLED`;
export const INIT_STREAMSPECEDIT_REJECTED = `${PREFIX}INIT_STREAMSPECEDIT_REJECTED`;
export const INIT_STREAMSPECEDIT_CANCELLED = `${PREFIX}INIT_STREAMSPECEDIT_CANCELLED`;

export const UNLOAD_STREAMSPEC = `${PREFIX}UNLOAD_STREAMSPEC`;
export const UNLOAD_STREAMSPECS = `${PREFIX}UNLOAD_STREAMSPECS`;

// For general API calls
export const FETCH_STREAMSPECS_REQUEST = `${PREFIX}FETCH_STREAMSPECS_REQUEST`;
export const FETCH_STREAMSPECS_FULFILLED = `${PREFIX}FETCH_STREAMSPECS_FULFILLED`;
export const FETCH_STREAMSPECS_REJECTED = `${PREFIX}FETCH_STREAMSPECS_REJECTED`;
export const FETCH_STREAMSPECS_CANCELLED = `${PREFIX}FETCH_STREAMSPECS_CANCELLED`;

export const CREATE_STREAMSPEC_REQUEST = `${PREFIX}CREATE_STREAMSPEC_REQUEST`;
export const CREATE_STREAMSPEC_FULFILLED = `${PREFIX}CREATE_STREAMSPEC_FULFILLED`;
export const CREATE_STREAMSPEC_REJECTED = `${PREFIX}CREATE_STREAMSPEC_REJECTED`;

export const UPDATE_STREAMSPEC_REQUEST = `${PREFIX}UPDATE_STREAMSPEC_REQUEST`;
export const UPDATE_STREAMSPEC_FULFILLED = `${PREFIX}UPDATE_STREAMSPEC_FULFILLED`;
export const UPDATE_STREAMSPEC_REJECTED = `${PREFIX}UPDATE_STREAMSPEC_REJECTED`;

export const DELETE_STREAMSPECS_REQUEST = `${PREFIX}DELETE_STREAMSPECS_REQUEST`;
export const DELETE_STREAMSPECS_FULFILLED = `${PREFIX}DELETE_STREAMSPECS_FULFILLED`;
export const DELETE_STREAMSPECS_REJECTED = `${PREFIX}DELETE_STREAMSPECS_REJECTED`;

export const DELETE_STREAMSPEC_REQUEST = `${PREFIX}DELETE_STREAMSPEC_REQUEST`;
export const DELETE_STREAMSPEC_FULFILLED = `${PREFIX}DELETE_STREAMSPEC_FULFILLED`;
export const DELETE_STREAMSPEC_REJECTED = `${PREFIX}DELETE_STREAMSPEC_REJECTED`;
