import { PREFIX } from '../../constants';

// For initializing the APPDEPLOYMENT create ui state
export const INIT_APPDEPLOYMENTCREATE_REQUEST = `${PREFIX}INIT_APPDEPLOYMENTCREATE_REQUEST`;
export const INIT_APPDEPLOYMENTCREATE_FULFILLED = `${PREFIX}INIT_APPDEPLOYMENTCREATE_FULFILLED`;
export const INIT_APPDEPLOYMENTCREATE_REJECTED = `${PREFIX}INIT_APPDEPLOYMENTCREATE_REJECTED`;
export const INIT_APPDEPLOYMENTCREATE_CANCELLED = `${PREFIX}INIT_APPDEPLOYMENTCREATE_CANCELLED`;

// Cleanup
export const UNLOAD_APPDEPLOYMENT = `${PREFIX}UNLOAD_APPDEPLOYMENT`;
export const UNLOAD_APPDEPLOYMENTS = `${PREFIX}UNLOAD_APPDEPLOYMENTS`;

// For general API calls
export const FETCH_APPDEPLOYMENTS_REQUEST = `${PREFIX}FETCH_APPDEPLOYMENTS_REQUEST`;
export const FETCH_APPDEPLOYMENTS_FULFILLED = `${PREFIX}FETCH_APPDEPLOYMENTS_FULFILLED`;
export const FETCH_APPDEPLOYMENTS_REJECTED = `${PREFIX}FETCH_APPDEPLOYMENTS_REJECTED`;
export const FETCH_APPDEPLOYMENTS_CANCELLED = `${PREFIX}FETCH_APPDEPLOYMENTS_CANCELLED`;

export const CREATE_APPDEPLOYMENT_REQUEST = `${PREFIX}CREATE_APPDEPLOYMENT_REQUEST`;
export const CREATE_APPDEPLOYMENT_FULFILLED = `${PREFIX}CREATE_APPDEPLOYMENT_FULFILLED`;
export const CREATE_APPDEPLOYMENT_REJECTED = `${PREFIX}CREATE_APPDEPLOYMENT_REJECTED`;

export const UPDATE_APPDEPLOYMENT_REQUEST = `${PREFIX}UPDATE_APPDEPLOYMENT_REQUEST`;
export const UPDATE_APPDEPLOYMENT_FULFILLED = `${PREFIX}UPDATE_APPDEPLOYMENT_FULFILLED`;
export const UPDATE_APPDEPLOYMENT_REJECTED = `${PREFIX}UPDATE_APPDEPLOYMENT_REJECTED`;

export const DELETE_APPDEPLOYMENTS_REQUEST = `${PREFIX}DELETE_APPDEPLOYMENTS_REQUEST`;
export const DELETE_APPDEPLOYMENT_REQUEST = `${PREFIX}DELETE_APPDEPLOYMENT_REQUEST`;
export const DELETE_APPDEPLOYMENT_FULFILLED = `${PREFIX}DELETE_APPDEPLOYMENT_FULFILLED`;
export const DELETE_APPDEPLOYMENT_REJECTED = `${PREFIX}DELETE_APPDEPLOYMENT_REJECTED`;
