export const FETCH_APIENDPOINTS_PENDING = 'apiendpoints/FETCH_APIENDPOINTS_PENDING';
export const FETCH_APIENDPOINTS_FULFILLED = 'apiendpoints/FETCH_APIENDPOINTS_FULFILLED';
export const FETCH_APIENDPOINTS_REJECTED = 'apiendpoints/FETCH_APIENDPOINTS_REJECTED';

export const FETCH_APIENDPOINT_PENDING = 'apiendpoints/FETCH_APIENDPOINT_PENDING';
export const FETCH_APIENDPOINT_FULFILLED = 'apiendpoints/FETCH_APIENDPOINT_FULFILLED';
export const FETCH_APIENDPOINT_REJECTED = 'apiendpoints/FETCH_APIENDPOINT_REJECTED';

export const CREATE_APIENDPOINT_PENDING = 'apiendpoints/CREATE_APIENDPOINT_PENDING';
export const CREATE_APIENDPOINT_FULFILLED = 'apiendpoints/CREATE_APIENDPOINT_FULFILLED';
export const CREATE_APIENDPOINT_REJECTED = 'apiendpoints/CREATE_APIENDPOINT_REJECTED';

export const UPDATE_APIENDPOINT_PENDING = 'apiendpoints/UPDATE_APIENDPOINT_PENDING';
export const UPDATE_APIENDPOINT_FULFILLED = 'apiendpoints/UPDATE_APIENDPOINT_FULFILLED';
export const UPDATE_APIENDPOINT_REJECTED = 'apiendpoints/UPDATE_APIENDPOINT_REJECTED';

export const DELETE_APIENDPOINT_PENDING = 'apiendpoints/DELETE_APIENDPOINT_PENDING';
export const DELETE_APIENDPOINT_FULFILLED = 'apiendpoints/DELETE_APIENDPOINT_FULFILLED';
export const DELETE_APIENDPOINT_REJECTED = 'apiendpoints/DELETE_APIENDPOINT_REJECTED';

export const SELECTED_APIENDPOINTS = 'apiendpoints/SELECTED_APIENDPOINTS';

export const APIENDPOINT_UNLOADED = 'apiendpoints/APIENDPOINT_UNLOADED';
export const APIENDPOINTS_UNLOADED = 'apiendpoints/APIENDPOINTS_UNLOADED';
