export const FETCH_POLICYRULES_PENDING = 'policyrules/FETCH_POLICYRULES_PENDING';
export const FETCH_POLICYRULES_FULFILLED = 'policyrules/FETCH_POLICYRULES_FULFILLED';
export const FETCH_POLICYRULES_REJECTED = 'policyrules/FETCH_POLICYRULES_REJECTED';

export const FETCH_POLICYRULE_PENDING = 'policyrules/FETCH_POLICYRULE_PENDING';
export const FETCH_POLICYRULE_FULFILLED = 'policyrules/FETCH_POLICYRULE_FULFILLED';
export const FETCH_POLICYRULE_REJECTED = 'policyrules/FETCH_POLICYRULE_REJECTED';

export const CREATE_POLICYRULE_PENDING = 'policyrules/CREATE_POLICYRULE_PENDING';
export const CREATE_POLICYRULE_FULFILLED = 'policyrules/CREATE_POLICYRULE_FULFILLED';
export const CREATE_POLICYRULE_REJECTED = 'policyrules/CREATE_POLICYRULE_REJECTED';

export const UPDATE_POLICYRULE_PENDING = 'policyrules/UPDATE_POLICYRULE_PENDING';
export const UPDATE_POLICYRULE_FULFILLED = 'policyrules/UPDATE_POLICYRULE_FULFILLED';
export const UPDATE_POLICYRULE_REJECTED = 'policyrules/UPDATE_POLICYRULE_REJECTED';

export const DELETE_POLICYRULE_PENDING = 'policyrules/DELETE_POLICYRULE_PENDING';
export const DELETE_POLICYRULE_FULFILLED = 'policyrules/DELETE_POLICYRULE_FULFILLED';
export const DELETE_POLICYRULE_REJECTED = 'policyrules/DELETE_POLICYRULE_REJECTED';

export const SELECTED_POLICYRULES = 'policyrules/SELECTED_POLICYRULES';

export const POLICYRULE_UNLOADED = 'policyrules/POLICYRULE_UNLOADED';
export const POLICYRULES_UNLOADED = 'policyrules/POLICYRULES_UNLOADED';

export const SELECTED_ACTIONS = 'policyrules/SELECTED_ACTIONS';

export const LAMBDAS_UNLOADED = 'policyrules/LAMBDAS_UNLOADED';
export const FETCH_LAMBDAS_PENDING = 'policyrules/FETCH_LAMBDAS_PENDING';
export const FETCH_LAMBDAS_FULFILLED = 'policyrules/FETCH_LAMBDAS_FULFILLED';
export const FETCH_LAMBDAS_REJECTED = 'policyrules/FETCH_LAMBDAS_REJECTED';
