import { PREFIX } from '../../constants';

// TODO: Migrate to INIT WORKFLOW pattern
export const FETCH_POLICYRULE_REQUEST = `${PREFIX}FETCH_POLICYRULE_REQUEST`;
export const FETCH_POLICYRULE_FULFILLED = `${PREFIX}FETCH_POLICYRULE_FULFILLED`;
export const FETCH_POLICYRULE_REJECTED = `${PREFIX}FETCH_POLICYRULE_REJECTED`;
export const FETCH_POLICYRULE_CANCELLED = `${PREFIX}FETCH_POLICYRULE_CANCELLED`;

// For general API calls
export const FETCH_POLICYRULES_REQUEST = `${PREFIX}FETCH_POLICYRULES_REQUEST`;
export const FETCH_POLICYRULES_FULFILLED = `${PREFIX}FETCH_POLICYRULES_FULFILLED`;
export const FETCH_POLICYRULES_REJECTED = `${PREFIX}FETCH_POLICYRULES_REJECTED`;
export const FETCH_POLICYRULES_CANCELLED = `${PREFIX}FETCH_POLICYRULES_CANCELLED`;

export const CREATE_POLICYRULE_REQUEST = `${PREFIX}CREATE_POLICYRULE_REQUEST`;
export const CREATE_POLICYRULE_FULFILLED = `${PREFIX}CREATE_POLICYRULE_FULFILLED`;
export const CREATE_POLICYRULE_REJECTED = `${PREFIX}CREATE_POLICYRULE_REJECTED`;

export const UPDATE_POLICYRULE_REQUEST = `${PREFIX}UPDATE_POLICYRULE_REQUEST`;
export const UPDATE_POLICYRULE_FULFILLED = `${PREFIX}UPDATE_POLICYRULE_FULFILLED`;
export const UPDATE_POLICYRULE_REJECTED = `${PREFIX}UPDATE_POLICYRULE_REJECTED`;

export const DELETE_POLICYRULES_REQUEST = `${PREFIX}DELETE_POLICYRULES_REQUEST`;
export const DELETE_POLICYRULES_FULFILLED = `${PREFIX}DELETE_POLICYRULES_FULFILLED`;
export const DELETE_POLICYRULES_REJECTED = `${PREFIX}DELETE_POLICYRULES_REJECTED`;

export const DELETE_POLICYRULE_REQUEST = `${PREFIX}DELETE_POLICYRULE_REQUEST`;
export const DELETE_POLICYRULE_FULFILLED = `${PREFIX}DELETE_POLICYRULE_FULFILLED`;
export const DELETE_POLICYRULE_REJECTED = `${PREFIX}DELETE_POLICYRULE_REJECTED`;

// Cleanup
export const UNLOAD_POLICYRULE = `${PREFIX}UNLOAD_POLICYRULE`;
export const UNLOAD_POLICYRULES = `${PREFIX}UNLOAD_POLICYRULES`;
