export const PREFIX = 'metaResource/';

/**
 * Search
 */
export const DO_SEARCHUSERS_REQUEST = `${PREFIX}DO_SEARCHUSERS_REQUEST`;
export const DO_SEARCHUSERS_FULFILLED = `${PREFIX}DO_SEARCHUSERS_FULFILLED`;
export const DO_SEARCHUSERS_REJECTED = `${PREFIX}DO_SEARCHUSERS_REJECTED`;
export const DO_SEARCHASSETS_REQUEST = `${PREFIX}DO_SEARCHASSETS_REQUEST`;
export const DO_SEARCHASSETS_FULFILLED = `${PREFIX}DO_SEARCHASSETS_FULFILLED`;
export const DO_SEARCHASSETS_REJECTED = `${PREFIX}DO_SEARCHASSETS_REJECTED`;

export const UNLOAD_SEARCHASSETS = `${PREFIX}UNLOAD_SEARCHASSETS`;
export const UNLOAD_SEARCHUSERS = `${PREFIX}UNLOAD_SEARCHUSERS`;
