export const FETCH_POLICIES_PENDING = 'policies/FETCH_POLICIES_PENDING';
export const FETCH_POLICIES_FULFILLED = 'policies/FETCH_POLICIES_FULFILLED';
export const FETCH_POLICIES_REJECTED = 'policies/FETCH_POLICIES_REJECTED';
