import { PREFIX } from '../../constants';

// TODO: Migrate to INIT WORKFLOW pattern
export const FETCH_POLICY_REQUEST = `${PREFIX}FETCH_POLICY_REQUEST`;
export const FETCH_POLICY_FULFILLED = `${PREFIX}FETCH_POLICY_FULFILLED`;
export const FETCH_POLICY_REJECTED = `${PREFIX}FETCH_POLICY_REJECTED`;
export const FETCH_POLICY_CANCELLED = `${PREFIX}FETCH_POLICY_CANCELLED`;

// For general API calls
export const FETCH_POLICIES_REQUEST = `${PREFIX}FETCH_POLICIES_REQUEST`;
export const FETCH_POLICIES_FULFILLED = `${PREFIX}FETCH_POLICIES_FULFILLED`;
export const FETCH_POLICIES_REJECTED = `${PREFIX}FETCH_POLICIES_REJECTED`;
export const FETCH_POLICIES_CANCELLED = `${PREFIX}FETCH_POLICIES_CANCELLED`;

export const CREATE_POLICY_REQUEST = `${PREFIX}CREATE_POLICY_REQUEST`;
export const CREATE_POLICY_FULFILLED = `${PREFIX}CREATE_POLICY_FULFILLED`;
export const CREATE_POLICY_REJECTED = `${PREFIX}CREATE_POLICY_REJECTED`;

export const UPDATE_POLICY_REQUEST = `${PREFIX}UPDATE_POLICY_REQUEST`;
export const UPDATE_POLICY_FULFILLED = `${PREFIX}UPDATE_POLICY_FULFILLED`;
export const UPDATE_POLICY_REJECTED = `${PREFIX}UPDATE_POLICY_REJECTED`;

export const DELETE_POLICIES_REQUEST = `${PREFIX}DELETE_POLICIES_REQUEST`;
export const DELETE_POLICIES_FULFILLED = `${PREFIX}DELETE_POLICIES_FULFILLED`;
export const DELETE_POLICIES_REJECTED = `${PREFIX}DELETE_POLICIES_REJECTED`;

export const DELETE_POLICY_REQUEST = `${PREFIX}DELETE_POLICY_REQUEST`;
export const DELETE_POLICY_FULFILLED = `${PREFIX}DELETE_POLICY_FULFILLED`;
export const DELETE_POLICY_REJECTED = `${PREFIX}DELETE_POLICY_REJECTED`;

// Cleanup
export const UNLOAD_POLICY = `${PREFIX}UNLOAD_POLICY`;
export const UNLOAD_POLICIES = `${PREFIX}UNLOAD_POLICIES`;
