export const FETCH_POLICIES_PENDING = 'policies/FETCH_POLICIES_PENDING';
export const FETCH_POLICIES_FULFILLED = 'policies/FETCH_POLICIES_FULFILLED';
export const FETCH_POLICIES_REJECTED = 'policies/FETCH_POLICIES_REJECTED';

export const FETCH_POLICY_PENDING = 'policies/FETCH_POLICY_PENDING';
export const FETCH_POLICY_FULFILLED = 'policies/FETCH_POLICY_FULFILLED';
export const FETCH_POLICY_REJECTED = 'policies/FETCH_POLICY_REJECTED';

export const CREATE_POLICY_PENDING = 'policies/CREATE_POLICY_PENDING';
export const CREATE_POLICY_FULFILLED = 'policies/CREATE_POLICY_FULFILLED';
export const CREATE_POLICY_REJECTED = 'policies/CREATE_POLICY_REJECTED';

export const UPDATE_POLICY_PENDING = 'policies/UPDATE_POLICY_PENDING';
export const UPDATE_POLICY_FULFILLED = 'policies/UPDATE_POLICY_FULFILLED';
export const UPDATE_POLICY_REJECTED = 'policies/UPDATE_POLICY_REJECTED';

export const DELETE_POLICY_PENDING = 'policies/DELETE_POLICY_PENDING';
export const DELETE_POLICY_FULFILLED = 'policies/DELETE_POLICY_FULFILLED';
export const DELETE_POLICY_REJECTED = 'policies/DELETE_POLICY_REJECTED';

export const SELECTED_POLICIES = 'policies/SELECTED_POLICIES';

export const POLICY_UNLOADED = 'policies/POLICY_UNLOADED';
export const POLICIES_UNLOADED = 'policies/POLICIES_UNLOADED';
