export const WORKSPACES_NAVIGATION = 'hierarchy/WORKSPACES_NAVIGATION';
export const UNLOAD_WORKSPACES_NAVIGATION = 'hierarchy/UNLOAD_WORKSPACES_NAVIGATION';
export const ENVIRONMENTS_NAVIGATION = 'hierarchy/ENVIRONMENTS_NAVIGATION';
export const UNLOAD_ENVIRONMENTS_NAVIGATION = 'hierarchy/UNLOAD_ENVIRONMENTS_NAVIGATION';
export const HIERARCHY_NAVIGATION = 'hierarchy/HIERARCHY_NAVIGATION';
export const UNLOAD_HIERARCHY_NAVIGATION = 'hierarchy/UNLOAD_HIERARCHY_NAVIGATION';
