import { PREFIX } from '../../constants';

export const PRE_CONTEXT_REQUEST = `${PREFIX}PRE_CONTEXT_REQUEST`;
export const FETCH_CONTEXT_REQUEST = `${PREFIX}FETCH_CONTEXT_REQUEST`;
export const FETCH_CONTEXT_FULFILLED = `${PREFIX}FETCH_CONTEXT_FULFILLED`;
export const FETCH_CONTEXT_REJECTED = `${PREFIX}FETCH_CONTEXT_REJECTED`;
export const UNLOAD_CONTEXT = `${PREFIX}UNLOAD_CONTEXT`;

export const CREATE_ORG_REQUEST = `${PREFIX}CREATE_ORG_REQUEST`;
export const CREATE_ORG_FULFILLED = `${PREFIX}CREATE_ORG_FULFILLED`;
export const CREATE_ORG_REJECTED = `${PREFIX}CREATE_ORG_REJECTED`;
export const UPDATE_ORG_REQUEST = `${PREFIX}UPDATE_ORG_REQUEST`;
export const UPDATE_ORG_FULFILLED = `${PREFIX}UPDATE_ORG_FULFILLED`;
export const UPDATE_ORG_REJECTED = `${PREFIX}UPDATE_ORG_REJECTED`;
export const DELETE_ORG_REQUEST = `${PREFIX}DELETE_ORG_REQUEST`;
export const DELETE_ORG_FULFILLED = `${PREFIX}DELETE_ORG_FULFILLED`;
export const DELETE_ORG_REJECTED = `${PREFIX}DELETE_ORG_REJECTED`;

export const CREATE_WORKSPACE_REQUEST = `${PREFIX}CREATE_WORKSPACE_REQUEST`;
export const CREATE_WORKSPACE_FULFILLED = `${PREFIX}CREATE_WORKSPACE_FULFILLED`;
export const CREATE_WORKSPACE_REJECTED = `${PREFIX}CREATE_WORKSPACE_REJECTED`;
export const UPDATE_WORKSPACE_REQUEST = `${PREFIX}UPDATE_WORKSPACE_REQUEST`;
export const UPDATE_WORKSPACE_FULFILLED = `${PREFIX}UPDATE_WORKSPACE_FULFILLED`;
export const UPDATE_WORKSPACE_REJECTED = `${PREFIX}UPDATE_WORKSPACE_REJECTED`;
export const DELETE_WORKSPACE_REQUEST = `${PREFIX}DELETE_WORKSPACE_REQUEST`;
export const DELETE_WORKSPACE_FULFILLED = `${PREFIX}DELETE_WORKSPACE_FULFILLED`;
export const DELETE_WORKSPACE_REJECTED = `${PREFIX}DELETE_WORKSPACE_REJECTED`;

export const CREATE_ENVIRONMENT_REQUEST = `${PREFIX}CREATE_ENVIRONMENT_REQUEST`;
export const CREATE_ENVIRONMENT_FULFILLED = `${PREFIX}CREATE_ENVIRONMENT_FULFILLED`;
export const CREATE_ENVIRONMENT_REJECTED = `${PREFIX}CREATE_ENVIRONMENT_REJECTED`;
export const UPDATE_ENVIRONMENT_REQUEST = `${PREFIX}UPDATE_ENVIRONMENT_REQUEST`;
export const UPDATE_ENVIRONMENT_FULFILLED = `${PREFIX}UPDATE_ENVIRONMENT_FULFILLED`;
export const UPDATE_ENVIRONMENT_REJECTED = `${PREFIX}UPDATE_ENVIRONMENT_REJECTED`;
export const DELETE_ENVIRONMENT_REQUEST = `${PREFIX}DELETE_ENVIRONMENT_REQUEST`;
export const DELETE_ENVIRONMENT_FULFILLED = `${PREFIX}DELETE_ENVIRONMENT_FULFILLED`;
export const DELETE_ENVIRONMENT_REJECTED = `${PREFIX}DELETE_ENVIRONMENT_REJECTED`;

/**
 * Orgs
 */
export const FETCH_ALLORGS_REQUEST = `${PREFIX}FETCH_ALLORGS_REQUEST`;
export const FETCH_ALLORGS_FULFILLED = `${PREFIX}FETCH_ALLORGS_FULFILLED`;
export const FETCH_ALLORGS_REJECTED = `${PREFIX}FETCH_ALLORGS_REJECTED`;

export const FETCH_ALLORGSDROPDOWN_REQUEST = `${PREFIX}FETCH_ALLORGSDROPDOWN_REQUEST`;
export const FETCH_ALLORGSDROPDOWN_FULFILLED = `${PREFIX}FETCH_ALLORGSDROPDOWN_FULFILLED`;
export const FETCH_ALLORGSDROPDOWN_REJECTED = `${PREFIX}FETCH_ALLORGSDROPDOWN_REJECTED`;

/**
 * Self
 */
export const FETCH_SELF_REQUEST = `${PREFIX}FETCH_SELF_REQUEST`;
export const FETCH_SELF_FULFILLED = `${PREFIX}FETCH_SELF_FULFILLED`;
export const FETCH_SELF_REJECTED = `${PREFIX}FETCH_SELF_REJECTED`;
