export const PREFIX = 'metaResource/';

/**
 * Environments
 */
export const UNLOAD_ENVIRONMENT = `${PREFIX}UNLOAD_ENVIRONMENT`;

/**
 * Orgs
 */
export const FETCH_ALLORGS_REQUEST = `${PREFIX}FETCH_ALLORGS_REQUEST`;
export const FETCH_ALLORGS_FULFILLED = `${PREFIX}FETCH_ALLORGS_FULFILLED`;
export const FETCH_ALLORGS_REJECTED = `${PREFIX}FETCH_ALLORGS_REJECTED`;

export const FETCH_ALLORGSDROPDOWN_REQUEST = `${PREFIX}FETCH_ALLORGSDROPDOWN_REQUEST`;
export const FETCH_ALLORGSDROPDOWN_FULFILLED = `${PREFIX}FETCH_ALLORGSDROPDOWN_FULFILLED`;
export const FETCH_ALLORGSDROPDOWN_REJECTED = `${PREFIX}FETCH_ALLORGSDROPDOWN_REJECTED`;

export const FETCH_ORGSET_REQUEST = `${PREFIX}FETCH_ORGSET_REQUEST`;
export const FETCH_ORGSET_FULFILLED = `${PREFIX}FETCH_ORGSET_FULFILLED`;
export const FETCH_ORGSET_REJECTED = `${PREFIX}FETCH_ORGSET_REJECTED`;

/**
 * Self
 */
export const FETCH_SELF_REQUEST = `${PREFIX}FETCH_SELF_REQUEST`;
export const FETCH_SELF_FULFILLED = `${PREFIX}FETCH_SELF_FULFILLED`;
export const FETCH_SELF_REJECTED = `${PREFIX}FETCH_SELF_REJECTED`;
