export const FETCH_ENTITLEMENTS_PENDING = 'entitlements/FETCH_ENTITLEMENTS_PENDING';
export const FETCH_ENTITLEMENTS_FULFILLED = 'entitlements/FETCH_ENTITLEMENTS_FULFILLED';
export const FETCH_ENTITLEMENTS_REJECTED = 'entitlements/FETCH_ENTITLEMENTS_REJECTED';

export const FETCH_IDENTITIES_PENDING = 'entitlements/FETCH_IDENTITIES_PENDING';
export const FETCH_IDENTITIES_FULFILLED = 'entitlements/FETCH_IDENTITIES_FULFILLED';
export const FETCH_IDENTITIES_REJECTED = 'entitlements/FETCH_IDENTITIES_REJECTED';

export const UPDATE_ENTITLEMENTS_PENDING = 'entitlements/UPDATE_ENTITLEMENTS_PENDING';
export const UPDATE_ENTITLEMENTS_FULFILLED = 'entitlements/UPDATE_ENTITLEMENTS_FULFILLED';
export const UPDATE_ENTITLEMENTS_REJECTED = 'entitlements/UPDATE_ENTITLEMENTS_REJECTED';

export const SELECTED_IDENTITY = 'entitlements/SELECTED_IDENTITY';

export const UDPATE_ENTITLEMENT_TOGGLE_STATE = 'entitlements/UDPATE_ENTITLEMENT_TOGGLE_STATE';

export const ENTITLEMENTS_UNLOADED = 'entitlements/ENTITLEMENTS_UNLOADED';

export const FILTER_IDENTITIES_TEXT = 'entitlements/FILTER_IDENTITIES_TEXT';
export const FILTER_IDENTITIES_TEXT_CLEAR = 'entitlements/FILTER_IDENTITIES_TEXT_CLEAR';
