export const PREFIX = 'metaResource/';


/**
 * Entitlements
 */
export const FETCH_ENTITLEMENTS_REQUEST = `${PREFIX}FETCH_ENTITLEMENTS_REQUEST`;
export const FETCH_ENTITLEMENTS_FULFILLED = `${PREFIX}FETCH_ENTITLEMENTS_FULFILLED`;
export const FETCH_ENTITLEMENTS_REJECTED = `${PREFIX}FETCH_ENTITLEMENTS_REJECTED`;

export const UPDATE_ENTITLEMENT_REQUEST = `${PREFIX}UPDATE_ENTITLEMENT_REQUEST`;
export const UPDATE_ENTITLEMENT_FULFILLED = `${PREFIX}UPDATE_ENTITLEMENT_FULFILLED`;
export const UPDATE_ENTITLEMENT_REJECTED = `${PREFIX}UPDATE_ENTITLEMENT_REJECTED`;

export const UNLOAD_ENTITLEMENTS = `${PREFIX}UNLOAD_ENTITLEMENTS`;
