export const FETCH_ENTITLEMENTS_PENDING = 'entitlements/FETCH_ENTITLEMENTS_PENDING';
export const FETCH_ENTITLEMENTS_FULFILLED = 'entitlements/FETCH_ENTITLEMENTS_FULFILLED';
export const FETCH_ENTITLEMENTS_REJECTED = 'entitlements/FETCH_ENTITLEMENTS_REJECTED';
