export const FETCH_USERS_PENDING = 'users/FETCH_USERS_PENDING';
export const FETCH_USERS_FULFILLED = 'users/FETCH_USERS_FULFILLED';
export const FETCH_USERS_REJECTED = 'users/FETCH_USERS_REJECTED';

export const FETCH_USER_PENDING = 'users/FETCH_USER_PENDING';
export const FETCH_USER_FULFILLED = 'users/FETCH_USER_FULFILLED';
export const FETCH_USER_REJECTED = 'users/FETCH_USER_REJECTED';

export const CREATE_USER_PENDING = 'users/CREATE_USER_PENDING';
export const CREATE_USER_FULFILLED = 'users/CREATE_USER_FULFILLED';
export const CREATE_USER_REJECTED = 'users/CREATE_USER_REJECTED';

export const UPDATE_USER_PENDING = 'users/UPDATE_USER_PENDING';
export const UPDATE_USER_FULFILLED = 'users/UPDATE_USER_FULFILLED';
export const UPDATE_USER_REJECTED = 'users/UPDATE_USER_REJECTED';

export const DELETE_USER_PENDING = 'users/DELETE_USER_PENDING';
export const DELETE_USER_FULFILLED = 'users/DELETE_USER_FULFILLED';
export const DELETE_USER_REJECTED = 'users/DELETE_USER_REJECTED';

export const FETCH_ALLORGS_PENDING = 'users/FETCH_ALLORGS_PENDING';
export const FETCH_ALLORGS_FULFILLED = 'users/FETCH_ALLORGS_FULFILLED';
export const FETCH_ALLORGS_REJECTED = 'users/FETCH_ALLORGS_REJECTED';

export const SELECTED_USERS = 'users/SELECTED_USERS';

export const USER_UNLOADED = 'users/USER_UNLOADED';
export const USERS_UNLOADED = 'users/USERS_UNLOADED';

