export const FETCH_ALLORGS_PENDING = 'orgnavmenu/FETCH_ALLORGS_PENDING';
export const FETCH_ALLORGS_FULFILLED = 'orgnavmenu/FETCH_ALLORGS_FULFILLED';
export const FETCH_ALLORGS_REJECTED = 'orgnavmenu/FETCH_ALLORGS_REJECTED';
export const FILTER_ALLORGS_TEXT = 'orgnavmenu/FILTER_ALLORGS_TEXT';

export const UNLOAD_ALLORGS = 'orgnavmenu/UNLOAD_ALLORGS';
