export const FETCH_ALLORGS_PENDING = 'app/FETCH_ALLORGS_PENDING';
export const FETCH_ALLORGS_FULFILLED = 'app/FETCH_ALLORGS_FULFILLED';
export const FETCH_ALLORGS_REJECTED = 'app/FETCH_ALLORGS_REJECTED';
export const FILTER_ALLORGS_TEXT = 'app/FILTER_ALLORGS_TEXT';
