/**
 * Actions for containment state management/switching. Typically, these are called when an org, workspace or
 * environment is navigated to.
 */
export const SET_CURRENT_ORG_CONTEXT_REQUEST = 'metaResource/SET_CURRENT_ORG_CONTEXT_REQUEST';
export const SET_CURRENT_ORG_CONTEXT_PENDING = 'metaResource/SET_CURRENT_ORG_CONTEXT_PENDING';
export const SET_CURRENT_ORG_CONTEXT_REJECTED = 'metaResource/SET_CURRENT_ORG_CONTEXT_REJECTED';

export const SET_CURRENT_WORKSPACE_CONTEXT_REQUEST = 'metaResource/SET_CURRENT_WORKSPACE_CONTEXT_REQUEST';
export const SET_CURRENT_WORKSPACE_CONTEXT_PENDING = 'metaResource/SET_CURRENT_WORKSPACE_CONTEXT_PENDING';
export const SET_CURRENT_WORKSPACE_CONTEXT_REJECTED = 'metaResource/SET_CURRENT_WORKSPACE_CONTEXT_REJECTED';

export const SET_CURRENT_ENVIRONMENT_CONTEXT_REQUEST = 'metaResource/SET_CURRENT_ENVIRONMENT_CONTEXT_REQUEST';
export const SET_CURRENT_ENVIRONMENT_CONTEXT_PENDING = 'metaResource/SET_CURRENT_ENVIRONMENT_CONTEXT_PENDING';
export const SET_CURRENT_ENVIRONMENT_CONTEXT_REJECTED = 'metaResource/SET_CURRENT_ENVIRONMENT_CONTEXT_REJECTED';

export const UPDATE_CURRENT_ORG_CONTEXT = 'metaResource/UPDATE_CURRENT_ORG_CONTEXT';
export const UPDATE_CURRENT_WORKSPACE_CONTEXT = 'metaResource/UPDATE_CURRENT_WORKSPACE_CONTEXT';
export const UPDATE_CURRENT_ENVIRONMENT_CONTEXT = 'metaResource/UPDATE_CURRENT_ENVIRONMENT_CONTEXT';

export const UNLOAD_CURRENT_WORKSPACE_CONTEXT = 'metaResource/UNLOAD_CURRENT_WORKSPACE_CONTEXT';
export const UNLOAD_CURRENT_ENVIRONMENT_CONTEXT = 'metaResource/UNLOAD_CURRENT_ENVIRONMENT_CONTEXT';

/**
 * Orgs
 */
export const FETCH_ALLORGS_REQUEST = 'metaResource/FETCH_ALLORGS_REQUEST';
export const FETCH_ALLORGS_FULFILLED = 'metaResource/FETCH_ALLORGS_FULFILLED';
export const FETCH_ALLORGS_REJECTED = 'metaResource/FETCH_ALLORGS_REJECTED';

export const FETCH_ORGS_REQUEST = 'metaResource/FETCH_ORGS_REQUEST';
export const FETCH_ORGS_FULFILLED = 'metaResource/FETCH_ORGS_FULFILLED';
export const FETCH_ORGS_REJECTED = 'metaResource/FETCH_ORGS_REJECTED';

export const FETCH_ORG_REQUEST = 'metaResource/FETCH_ORG_REQUEST';
export const FETCH_ORG_FULFILLED = 'metaResource/FETCH_ORG_FULFILLED';
export const FETCH_ORG_REJECTED = 'metaResource/FETCH_ORG_REJECTED';

export const FETCH_ORGSET_REQUEST = 'metaResource/FETCH_ORGSET_REQUEST';
export const FETCH_ORGSET_FULFILLED = 'metaResource/FETCH_ORGSET_FULFILLED';
export const FETCH_ORGSET_REJECTED = 'metaResource/FETCH_ORGSET_REJECTED';

export const CREATE_ORG_REQUEST = 'metaResource/CREATE_ORG_REQUEST';
export const CREATE_ORG_FULFILLED = 'metaResource/CREATE_ORG_FULFILLED';
export const CREATE_ORG_REJECTED = 'metaResource/CREATE_ORG_REJECTED';

export const UPDATE_ORG_REQUEST = 'metaResource/UPDATE_ORG_REQUEST';
export const UPDATE_ORG_FULFILLED = 'metaResource/UPDATE_ORG_FULFILLED';
export const UPDATE_ORG_REJECTED = 'metaResource/UPDATE_ORG_REJECTED';

export const DELETE_ORG_REQUEST = 'metaResource/DELETE_ORG_REQUEST';
export const DELETE_ORG_FULFILLED = 'metaResource/DELETE_ORG_FULFILLED';
export const DELETE_ORG_REJECTED = 'metaResource/DELETE_ORG_REJECTED';

export const UNLOAD_ORG = 'metaResource/UNLOAD_ORG';
export const UNLOAD_ORGS = 'metaResource/UNLOAD_ORGS';
export const UNLOAD_ORGSET = 'metaResource/UNLOAD_ORGSET';
export const UNLOAD_ALLORGS = 'metaResource/UNLOAD_ALLORGS';

/**
 * Workspaces
 */
export const FETCH_WORKSPACES_REQUEST = 'metaResource/FETCH_WORKSPACES_REQUEST';
export const FETCH_WORKSPACES_FULFILLED = 'metaResource/FETCH_WORKSPACES_FULFILLED';
export const FETCH_WORKSPACES_REJECTED = 'metaResource/FETCH_WORKSPACES_REJECTED';

export const FETCH_WORKSPACE_REQUEST = 'metaResource/FETCH_WORKSPACE_REQUEST';
export const FETCH_WORKSPACE_FULFILLED = 'metaResource/FETCH_WORKSPACE_FULFILLED';
export const FETCH_WORKSPACE_REJECTED = 'metaResource/FETCH_WORKSPACE_REJECTED';

export const CREATE_WORKSPACE_REQUEST = 'metaResource/CREATE_WORKSPACE_REQUEST';
export const CREATE_WORKSPACE_FULFILLED = 'metaResource/CREATE_WORKSPACE_FULFILLED';
export const CREATE_WORKSPACE_REJECTED = 'metaResource/CREATE_WORKSPACE_REJECTED';

export const UPDATE_WORKSPACE_REQUEST = 'metaResource/UPDATE_WORKSPACE_REQUEST';
export const UPDATE_WORKSPACE_FULFILLED = 'metaResource/UPDATE_WORKSPACE_FULFILLED';
export const UPDATE_WORKSPACE_REJECTED = 'metaResource/UPDATE_WORKSPACE_REJECTED';

export const DELETE_WORKSPACE_REQUEST = 'metaResource/DELETE_WORKSPACE_REQUEST';
export const DELETE_WORKSPACE_FULFILLED = 'metaResource/DELETE_WORKSPACE_FULFILLED';
export const DELETE_WORKSPACE_REJECTED = 'metaResource/DELETE_WORKSPACE_REJECTED';

export const UNLOAD_WORKSPACE = 'metaResource/UNLOAD_WORKSPACE';
export const UNLOAD_WORKSPACES = 'metaResource/UNLOAD_WORKSPACES';

/**
 * Environments
 */
export const FETCH_ENVIRONMENTS_REQUEST = 'metaResource/FETCH_ENVIRONMENTS_REQUEST';
export const FETCH_ENVIRONMENTS_FULFILLED = 'metaResource/FETCH_ENVIRONMENTS_FULFILLED';
export const FETCH_ENVIRONMENTS_REJECTED = 'metaResource/FETCH_ENVIRONMENTS_REJECTED';

export const FETCH_ENVIRONMENT_REQUEST = 'metaResource/FETCH_ENVIRONMENT_REQUEST';
export const FETCH_ENVIRONMENT_FULFILLED = 'metaResource/FETCH_ENVIRONMENT_FULFILLED';
export const FETCH_ENVIRONMENT_REJECTED = 'metaResource/FETCH_ENVIRONMENT_REJECTED';

export const CREATE_ENVIRONMENT_REQUEST = 'metaResource/CREATE_ENVIRONMENT_REQUEST';
export const CREATE_ENVIRONMENT_FULFILLED = 'metaResource/CREATE_ENVIRONMENT_FULFILLED';
export const CREATE_ENVIRONMENT_REJECTED = 'metaResource/CREATE_ENVIRONMENT_REJECTED';

export const UPDATE_ENVIRONMENT_REQUEST = 'metaResource/UPDATE_ENVIRONMENT_REQUEST';
export const UPDATE_ENVIRONMENT_FULFILLED = 'metaResource/UPDATE_ENVIRONMENT_FULFILLED';
export const UPDATE_ENVIRONMENT_REJECTED = 'metaResource/UPDATE_ENVIRONMENT_REJECTED';

export const DELETE_ENVIRONMENT_REQUEST = 'metaResource/DELETE_ENVIRONMENT_REQUEST';
export const DELETE_ENVIRONMENT_FULFILLED = 'metaResource/DELETE_ENVIRONMENT_FULFILLED';
export const DELETE_ENVIRONMENT_REJECTED = 'metaResource/DELETE_ENVIRONMENT_REJECTED';

export const UNLOAD_ENVIRONMENT = 'metaResource/UNLOAD_ENVIRONMENT';
export const UNLOAD_ENVIRONMENTS = 'metaResource/UNLOAD_ENVIRONMENTS';

/**
 * Self
 */
export const FETCH_SELF_REQUEST = 'metaResource/FETCH_SELF_REQUEST';
export const FETCH_SELF_FULFILLED = 'metaResource/FETCH_SELF_FULFILLED';
export const FETCH_SELF_REJECTED = 'metaResource/FETCH_SELF_REJECTED';

/**
 * Lambdas
 */
export const FETCH_LAMBDAS_REQUEST = 'metaResource/FETCH_LAMBDAS_REQUEST';
export const FETCH_LAMBDAS_FULFILLED = 'metaResource/FETCH_LAMBDAS_FULFILLED';
export const FETCH_LAMBDAS_REJECTED = 'metaResource/FETCH_LAMBDAS_REJECTED';

export const FETCH_LAMBDA_REQUEST = 'metaResource/FETCH_LAMBDA_REQUEST';
export const FETCH_LAMBDA_FULFILLED = 'metaResource/FETCH_LAMBDA_FULFILLED';
export const FETCH_LAMBDA_REJECTED = 'metaResource/FETCH_LAMBDA_REJECTED';

export const CREATE_LAMBDA_REQUEST = 'metaResource/CREATE_LAMBDA_REQUEST';
export const CREATE_LAMBDA_FULFILLED = 'metaResource/CREATE_LAMBDA_FULFILLED';
export const CREATE_LAMBDA_REJECTED = 'metaResource/CREATE_LAMBDA_REJECTED';

export const UPDATE_LAMBDA_REQUEST = 'metaResource/UPDATE_LAMBDA_REQUEST';
export const UPDATE_LAMBDA_FULFILLED = 'metaResource/UPDATE_LAMBDA_FULFILLED';
export const UPDATE_LAMBDA_REJECTED = 'metaResource/UPDATE_LAMBDA_REJECTED';

export const DELETE_LAMBDAS_REQUEST = 'metaResource/DELETE_LAMBDAS_REQUEST';
export const DELETE_LAMBDA_REQUEST = 'metaResource/DELETE_LAMBDA_REQUEST';
export const DELETE_LAMBDA_FULFILLED = 'metaResource/DELETE_LAMBDA_FULFILLED';
export const DELETE_LAMBDA_REJECTED = 'metaResource/DELETE_LAMBDA_REJECTED';

export const UNLOAD_LAMBDA = 'metaResource/UNLOAD_LAMBDA';
export const UNLOAD_LAMBDAS = 'metaResource/UNLOAD_LAMBDAS';

/**
 * APIS
 */
export const FETCH_APIS_REQUEST = 'metaResource/FETCH_APIS_REQUEST';
export const FETCH_APIS_FULFILLED = 'metaResource/FETCH_APIS_FULFILLED';
export const FETCH_APIS_REJECTED = 'metaResource/FETCH_APIS_REJECTED';

export const FETCH_API_REQUEST = 'metaResource/FETCH_API_REQUEST';
export const FETCH_API_FULFILLED = 'metaResource/FETCH_API_FULFILLED';
export const FETCH_API_REJECTED = 'apis/FETCH_API_REJECTED';

export const CREATE_API_REQUEST = 'metaResource/CREATE_API_REQUEST';
export const CREATE_API_FULFILLED = 'metaResource/CREATE_API_FULFILLED';
export const CREATE_API_REJECTED = 'metaResource/CREATE_API_REJECTED';

export const UPDATE_API_REQUEST = 'metaResource/UPDATE_API_REQUEST';
export const UPDATE_API_FULFILLED = 'metaResource/UPDATE_API_FULFILLED';
export const UPDATE_API_REJECTED = 'metaResource/UPDATE_API_REJECTED';

export const DELETE_APIS_REQUEST = 'metaResource/DELETE_APIS_REQUEST';
export const DELETE_API_REQUEST = 'metaResource/DELETE_API_REQUEST';
export const DELETE_API_FULFILLED = 'metaResource/DELETE_API_FULFILLED';
export const DELETE_API_REJECTED = 'metaResource/DELETE_API_REJECTED';

/**
 * API Endpoints
 */
export const FETCH_APIENDPOINTS_REQUEST = 'metaResource/FETCH_APIENDPOINTS_REQUEST';
export const FETCH_APIENDPOINTS_FULFILLED = 'metaResource/FETCH_APIENDPOINTS_FULFILLED';
export const FETCH_APIENDPOINTS_REJECTED = 'metaResource/FETCH_APIENDPOINTS_REJECTED';

export const FETCH_APIENDPOINT_REQUEST = 'metaResource/FETCH_APIENDPOINT_REQUEST';
export const FETCH_APIENDPOINT_FULFILLED = 'metaResource/FETCH_APIENDPOINT_FULFILLED';
export const FETCH_APIENDPOINT_REJECTED = 'metaResource/FETCH_APIENDPOINT_REJECTED';

export const CREATE_APIENDPOINT_REQUEST = 'metaResource/CREATE_APIENDPOINT_REQUEST';
export const CREATE_APIENDPOINT_FULFILLED = 'metaResource/CREATE_APIENDPOINT_FULFILLED';
export const CREATE_APIENDPOINT_REJECTED = 'metaResource/CREATE_APIENDPOINT_REJECTED';

export const UPDATE_APIENDPOINT_REQUEST = 'metaResource/UPDATE_APIENDPOINT_REQUEST';
export const UPDATE_APIENDPOINT_FULFILLED = 'metaResource/UPDATE_APIENDPOINT_FULFILLED';
export const UPDATE_APIENDPOINT_REJECTED = 'metaResource/UPDATE_APIENDPOINT_REJECTED';

export const DELETE_APIENDPOINTS_REQUEST = 'metaResource/DELETE_APIENDPOINTS_REQUEST';
export const DELETE_APIENDPOINT_REQUEST = 'metaResource/DELETE_APIENDPOINT_REQUEST';
export const DELETE_APIENDPOINT_FULFILLED = 'metaResource/DELETE_APIENDPOINT_FULFILLED';
export const DELETE_APIENDPOINT_REJECTED = 'metaResource/DELETE_APIENDPOINT_REJECTED';

/**
 * Providers
 */
export const FETCH_PROVIDERS_REQUEST = 'metaResource/FETCH_PROVIDERS_REQUEST';
export const FETCH_PROVIDERS_FULFILLED = 'metaResource/FETCH_PROVIDERS_FULFILLED';
export const FETCH_PROVIDERS_REJECTED = 'metaResource/FETCH_PROVIDERS_REJECTED';

export const FETCH_PROVIDER_REQUEST = 'metaResource/FETCH_PROVIDER_REQUEST';
export const FETCH_PROVIDER_FULFILLED = 'metaResource/FETCH_PROVIDER_FULFILLED';
export const FETCH_PROVIDER_REJECTED = 'metaResource/FETCH_PROVIDER_REJECTED';

export const CREATE_PROVIDER_REQUEST = 'metaResource/CREATE_PROVIDER_REQUEST';
export const CREATE_PROVIDER_FULFILLED = 'metaResource/CREATE_PROVIDER_FULFILLED';
export const CREATE_PROVIDER_REJECTED = 'metaResource/CREATE_PROVIDER_REJECTED';

export const UPDATE_PROVIDER_REQUEST = 'metaResource/UPDATE_PROVIDER_REQUEST';
export const UPDATE_PROVIDER_FULFILLED = 'metaResource/UPDATE_PROVIDER_FULFILLED';
export const UPDATE_PROVIDER_REJECTED = 'metaResource/UPDATE_PROVIDER_REJECTED';

export const DELETE_PROVIDERS_REQUEST = 'metaResource/DELETE_PROVIDERS_REQUEST';
export const DELETE_PROVIDER_REQUEST = 'metaResource/DELETE_PROVIDER_REQUEST';
export const DELETE_PROVIDER_FULFILLED = 'metaResource/DELETE_PROVIDER_FULFILLED';
export const DELETE_PROVIDER_REJECTED = 'metaResource/DELETE_PROVIDER_REJECTED';

export const FETCH_PROVIDERS_BYTYPE_REQUEST = 'metaResource/FETCH_PROVIDERS_BYTYPE_REQUEST';
export const FETCH_PROVIDERS_BYTYPE_FULFILLED = 'metaResource/FETCH_PROVIDERS_BYTYPE_FULFILLED';
export const FETCH_PROVIDERS_BYTYPE_REJECTED = 'metaResource/FETCH_PROVIDERS_BYTYPE_REJECTED';

export const FETCH_EXECUTORS_REQUEST = 'metaResource/FETCH_EXECUTORS_REQUEST';
export const FETCH_EXECUTORS_FULFILLED = 'metaResource/FETCH_EXECUTORS_FULFILLED';
export const FETCH_EXECUTORS_REJECTED = 'metaResource/FETCH_EXECUTORS_REJECTED';

/**
 * Env Vars
 */
export const FETCH_ENV_REQUEST = 'lambdas/FETCH_ENV_REQUEST';
export const FETCH_ENV_FULFILLED = 'lambdas/FETCH_ENV_FULFILLED';
export const FETCH_ENV_REJECTED = 'lambdas/FETCH_ENV_REJECTED';
