export const PREFIX = 'metaResource/';

/**
 * Orgs
 */
export const FETCH_ALLORGS_REQUEST = `${PREFIX}FETCH_ALLORGS_REQUEST`;
export const FETCH_ALLORGS_FULFILLED = `${PREFIX}FETCH_ALLORGS_FULFILLED`;
export const FETCH_ALLORGS_REJECTED = `${PREFIX}FETCH_ALLORGS_REJECTED`;

export const FETCH_ALLORGS_DROPDOWN_REQUEST = `${PREFIX}FETCH_ALLORGS_DROPDOWN_REQUEST`;
export const FETCH_ALLORGS_DROPDOWN_FULFILLED = `${PREFIX}FETCH_ALLORGS_DROPDOWN_FULFILLED`;
export const FETCH_ALLORGS_DROPDOWN_REJECTED = `${PREFIX}FETCH_ALLORGS_DROPDOWN_REJECTED`;

export const FETCH_ORGS_REQUEST = `${PREFIX}FETCH_ORGS_REQUEST`;
export const FETCH_ORGS_FULFILLED = `${PREFIX}FETCH_ORGS_FULFILLED`;
export const FETCH_ORGS_REJECTED = `${PREFIX}FETCH_ORGS_REJECTED`;

export const FETCH_ORG_REQUEST = `${PREFIX}FETCH_ORG_REQUEST`;
export const FETCH_ORG_FULFILLED = `${PREFIX}FETCH_ORG_FULFILLED`;
export const FETCH_ORG_REJECTED = `${PREFIX}FETCH_ORG_REJECTED`;

export const FETCH_ORGSET_REQUEST = `${PREFIX}FETCH_ORGSET_REQUEST`;
export const FETCH_ORGSET_FULFILLED = `${PREFIX}FETCH_ORGSET_FULFILLED`;
export const FETCH_ORGSET_REJECTED = `${PREFIX}FETCH_ORGSET_REJECTED`;

export const CREATE_ORG_REQUEST = `${PREFIX}CREATE_ORG_REQUEST`;
export const CREATE_ORG_FULFILLED = `${PREFIX}CREATE_ORG_FULFILLED`;
export const CREATE_ORG_REJECTED = `${PREFIX}CREATE_ORG_REJECTED`;

export const UPDATE_ORG_REQUEST = `${PREFIX}UPDATE_ORG_REQUEST`;
export const UPDATE_ORG_FULFILLED = `${PREFIX}UPDATE_ORG_FULFILLED`;
export const UPDATE_ORG_REJECTED = `${PREFIX}UPDATE_ORG_REJECTED`;

export const DELETE_ORG_REQUEST = `${PREFIX}DELETE_ORG_REQUEST`;
export const DELETE_ORG_FULFILLED = `${PREFIX}DELETE_ORG_FULFILLED`;
export const DELETE_ORG_REJECTED = `${PREFIX}DELETE_ORG_REJECTED`;

export const UNLOAD_ALLORGS = `${PREFIX}UNLOAD_ALLORGS`;
export const UNLOAD_ORGSET = `${PREFIX}UNLOAD_ORGSET`;
export const UNLOAD_ORGANIZATION = `${PREFIX}UNLOAD_ORGANIZATION`;

/**
 * Workspaces
 */
export const FETCH_WORKSPACES_REQUEST = `${PREFIX}FETCH_WORKSPACES_REQUEST`;
export const FETCH_WORKSPACES_FULFILLED = `${PREFIX}FETCH_WORKSPACES_FULFILLED`;
export const FETCH_WORKSPACES_REJECTED = `${PREFIX}FETCH_WORKSPACES_REJECTED`;

export const FETCH_WORKSPACE_REQUEST = `${PREFIX}FETCH_WORKSPACE_REQUEST`;
export const FETCH_WORKSPACE_FULFILLED = `${PREFIX}FETCH_WORKSPACE_FULFILLED`;
export const FETCH_WORKSPACE_REJECTED = `${PREFIX}FETCH_WORKSPACE_REJECTED`;

export const CREATE_WORKSPACE_REQUEST = `${PREFIX}CREATE_WORKSPACE_REQUEST`;
export const CREATE_WORKSPACE_FULFILLED = `${PREFIX}CREATE_WORKSPACE_FULFILLED`;
export const CREATE_WORKSPACE_REJECTED = `${PREFIX}CREATE_WORKSPACE_REJECTED`;

export const UPDATE_WORKSPACE_REQUEST = `${PREFIX}UPDATE_WORKSPACE_REQUEST`;
export const UPDATE_WORKSPACE_FULFILLED = `${PREFIX}UPDATE_WORKSPACE_FULFILLED`;
export const UPDATE_WORKSPACE_REJECTED = `${PREFIX}UPDATE_WORKSPACE_REJECTED`;

export const DELETE_WORKSPACE_REQUEST = `${PREFIX}DELETE_WORKSPACE_REQUEST`;
export const DELETE_WORKSPACE_FULFILLED = `${PREFIX}DELETE_WORKSPACE_FULFILLED`;
export const DELETE_WORKSPACE_REJECTED = `${PREFIX}DELETE_WORKSPACE_REJECTED`;

export const UNLOAD_WORKSPACES = `${PREFIX}UNLOAD_WORKSPACES`;
export const UNLOAD_WORKSPACE = `${PREFIX}UNLOAD_WORKSPACE`;

/**
 * Self
 */
export const FETCH_SELF_REQUEST = `${PREFIX}FETCH_SELF_REQUEST`;
export const FETCH_SELF_FULFILLED = `${PREFIX}FETCH_SELF_FULFILLED`;
export const FETCH_SELF_REJECTED = `${PREFIX}FETCH_SELF_REJECTED`;

/**
 * Lambdas
 */
export const FETCH_LAMBDAS_REQUEST = `${PREFIX}FETCH_LAMBDAS_REQUEST`;
export const FETCH_LAMBDAS_FULFILLED = `${PREFIX}FETCH_LAMBDAS_FULFILLED`;
export const FETCH_LAMBDAS_REJECTED = `${PREFIX}FETCH_LAMBDAS_REJECTED`;

export const FETCH_LAMBDA_REQUEST = `${PREFIX}FETCH_LAMBDA_REQUEST`;
export const FETCH_LAMBDA_FULFILLED = `${PREFIX}FETCH_LAMBDA_FULFILLED`;
export const FETCH_LAMBDA_REJECTED = `${PREFIX}FETCH_LAMBDA_REJECTED`;

export const CREATE_LAMBDA_REQUEST = `${PREFIX}CREATE_LAMBDA_REQUEST`;
export const CREATE_LAMBDA_FULFILLED = `${PREFIX}CREATE_LAMBDA_FULFILLED`;
export const CREATE_LAMBDA_REJECTED = `${PREFIX}CREATE_LAMBDA_REJECTED`;

export const UPDATE_LAMBDA_REQUEST = `${PREFIX}UPDATE_LAMBDA_REQUEST`;
export const UPDATE_LAMBDA_FULFILLED = `${PREFIX}UPDATE_LAMBDA_FULFILLED`;
export const UPDATE_LAMBDA_REJECTED = `${PREFIX}UPDATE_LAMBDA_REJECTED`;

export const DELETE_LAMBDAS_REQUEST = `${PREFIX}DELETE_LAMBDAS_REQUEST`;
export const DELETE_LAMBDA_REQUEST = `${PREFIX}DELETE_LAMBDA_REQUEST`;
export const DELETE_LAMBDA_FULFILLED = `${PREFIX}DELETE_LAMBDA_FULFILLED`;
export const DELETE_LAMBDA_REJECTED = `${PREFIX}DELETE_LAMBDA_REJECTED`;

export const UNLOAD_LAMBDAS = `${PREFIX}UNLOAD_LAMBDAS`;
export const UNLOAD_LAMBDA = `${PREFIX}UNLOAD_LAMBDA`;

/**
 * Providers
 */
export const FETCH_PROVIDERS_REQUEST = `${PREFIX}FETCH_PROVIDERS_REQUEST`;
export const FETCH_PROVIDERS_FULFILLED = `${PREFIX}FETCH_PROVIDERS_FULFILLED`;
export const FETCH_PROVIDERS_REJECTED = `${PREFIX}FETCH_PROVIDERS_REJECTED`;

export const FETCH_PROVIDER_REQUEST = `${PREFIX}FETCH_PROVIDER_REQUEST`;
export const FETCH_PROVIDER_FULFILLED = `${PREFIX}FETCH_PROVIDER_FULFILLED`;
export const FETCH_PROVIDER_REJECTED = `${PREFIX}FETCH_PROVIDER_REJECTED`;

export const CREATE_PROVIDER_REQUEST = `${PREFIX}CREATE_PROVIDER_REQUEST`;
export const CREATE_PROVIDER_FULFILLED = `${PREFIX}CREATE_PROVIDER_FULFILLED`;
export const CREATE_PROVIDER_REJECTED = `${PREFIX}CREATE_PROVIDER_REJECTED`;

export const UPDATE_PROVIDER_REQUEST = `${PREFIX}UPDATE_PROVIDER_REQUEST`;
export const UPDATE_PROVIDER_FULFILLED = `${PREFIX}UPDATE_PROVIDER_FULFILLED`;
export const UPDATE_PROVIDER_REJECTED = `${PREFIX}UPDATE_PROVIDER_REJECTED`;

export const DELETE_PROVIDERS_REQUEST = `${PREFIX}DELETE_PROVIDERS_REQUEST`;
export const DELETE_PROVIDERS_FULFILLED = `${PREFIX}DELETE_PROVIDERS_FULFILLED`;
export const DELETE_PROVIDERS_REJECTED = `${PREFIX}DELETE_PROVIDERS_REJECTED`;

export const DELETE_PROVIDER_REQUEST = `${PREFIX}DELETE_PROVIDER_REQUEST`;
export const DELETE_PROVIDER_FULFILLED = `${PREFIX}DELETE_PROVIDER_FULFILLED`;
export const DELETE_PROVIDER_REJECTED = `${PREFIX}DELETE_PROVIDER_REJECTED`;

export const FETCH_PROVIDERS_KONG_GATEWAY_REQUEST = `${PREFIX}FETCH_PROVIDERS_KONG_GATEWAY_REQUEST`;
export const FETCH_PROVIDERS_KONG_GATEWAY_FULFILLED = `${PREFIX}FETCH_PROVIDERS_KONG_GATEWAY_FULFILLED`;
export const FETCH_PROVIDERS_KONG_GATEWAY_REJECTED = `${PREFIX}FETCH_PROVIDERS_KONG_GATEWAY_REJECTED`;

export const REDEPLOY_PROVIDER_REQUEST = `${PREFIX}REDEPLOY_PROVIDER_REQUEST`;
export const REDEPLOY_PROVIDER_FULFILLED = `${PREFIX}REDEPLOY_PROVIDER_FULFILLED`;
export const REDEPLOY_PROVIDER_REJECTED = `${PREFIX}REDEPLOY_PROVIDER_REJECTED`;

export const UNLOAD_PROVIDERS = `${PREFIX}UNLOAD_PROVIDERS`;
export const UNLOAD_PROVIDER = `${PREFIX}UNLOAD_PROVIDER`;

/**
 * Containers
 */
export const FETCH_CONTAINERS_REQUEST = `${PREFIX}FETCH_CONTAINERS_REQUEST`;
export const FETCH_CONTAINERS_FULFILLED = `${PREFIX}FETCH_CONTAINERS_FULFILLED`;
export const FETCH_CONTAINERS_REJECTED = `${PREFIX}FETCH_CONTAINERS_REJECTED`;

export const FETCH_CONTAINER_REQUEST = `${PREFIX}FETCH_CONTAINER_REQUEST`;
export const FETCH_CONTAINER_FULFILLED = `${PREFIX}FETCH_CONTAINER_FULFILLED`;
export const FETCH_CONTAINER_REJECTED = `${PREFIX}FETCH_CONTAINER_REJECTED`;

export const FETCH_PROVIDERCONTAINER_REQUEST = `${PREFIX}FETCH_PROVIDERCONTAINER_REQUEST`;
export const CREATE_CONTAINER_REQUEST = `${PREFIX}CREATE_CONTAINER_REQUEST`;
export const CREATE_CONTAINER_FULFILLED = `${PREFIX}CREATE_CONTAINER_FULFILLED`;
export const CREATE_CONTAINER_REJECTED = `${PREFIX}CREATE_CONTAINER_REJECTED`;

export const UPDATE_CONTAINER_REQUEST = `${PREFIX}UPDATE_CONTAINER_REQUEST`;
export const UPDATE_CONTAINER_FULFILLED = `${PREFIX}UPDATE_CONTAINER_FULFILLED`;
export const UPDATE_CONTAINER_REJECTED = `${PREFIX}UPDATE_CONTAINER_REJECTED`;

export const DELETE_CONTAINER_REQUEST = `${PREFIX}DELETE_CONTAINER_REQUEST`;
export const DELETE_CONTAINER_FULFILLED = `${PREFIX}DELETE_CONTAINER_FULFILLED`;
export const DELETE_CONTAINER_REJECTED = `${PREFIX}DELETE_CONTAINER_REJECTED`;

export const SCALE_CONTAINER_REQUEST = `${PREFIX}SCALE_CONTAINER_REQUEST`;
export const SCALE_CONTAINER_FULFILLED = `${PREFIX}SCALE_CONTAINER_FULFILLED`;
export const SCALE_CONTAINER_REJECTED = `${PREFIX}SCALE_CONTAINER_REJECTED`;

export const MIGRATE_CONTAINER_REQUEST = `${PREFIX}MIGRATE_CONTAINER_REQUEST`;
export const MIGRATE_CONTAINER_FULFILLED = `${PREFIX}MIGRATE_CONTAINER_FULFILLED`;
export const MIGRATE_CONTAINER_REJECTED = `${PREFIX}MIGRATE_CONTAINER_REJECTED`;

export const PROMOTE_CONTAINER_REQUEST = `${PREFIX}PROMOTE_CONTAINER_REQUEST`;
export const PROMOTE_CONTAINER_FULFILLED = `${PREFIX}PROMOTE_CONTAINER_FULFILLED`;
export const PROMOTE_CONTAINER_REJECTED = `${PREFIX}PROMOTE_CONTAINER_REJECTED`;

export const FETCH_CONTAINERS_DROPDOWN_REQUEST = `${PREFIX}FETCH_CONTAINERS_DROPDOWN_REQUEST`;
export const FETCH_CONTAINERS_DROPDOWN_FULFILLED = `${PREFIX}FETCH_CONTAINERS_DROPDOWN_FULFILLED`;
export const FETCH_CONTAINERS_DROPDOWN_REJECTED = `${PREFIX}FETCH_CONTAINERS_DROPDOWN_REJECTED`;

export const UNLOAD_CONTAINERS = `${PREFIX}UNLOAD_CONTAINERS`;
export const UNLOAD_CONTAINER = `${PREFIX}UNLOAD_CONTAINER`;

/**
 * Entitlements
 */
export const FETCH_ENTITLEMENTS_REQUEST = `${PREFIX}FETCH_ENTITLEMENTS_REQUEST`;
export const FETCH_ENTITLEMENTS_FULFILLED = `${PREFIX}FETCH_ENTITLEMENTS_FULFILLED`;
export const FETCH_ENTITLEMENTS_REJECTED = `${PREFIX}FETCH_ENTITLEMENTS_REJECTED`;

export const UPDATE_ENTITLEMENT_REQUEST = `${PREFIX}UPDATE_ENTITLEMENT_REQUEST`;
export const UPDATE_ENTITLEMENT_FULFILLED = `${PREFIX}UPDATE_ENTITLEMENT_FULFILLED`;
export const UPDATE_ENTITLEMENT_REJECTED = `${PREFIX}UPDATE_ENTITLEMENT_REJECTED`;

export const UNLOAD_ENTITLEMENTS = `${PREFIX}UNLOAD_ENTITLEMENTS`;

/**
 * Users
 */
export const FETCH_USERS_REQUEST = `${PREFIX}FETCH_USERS_REQUEST`;
export const FETCH_USERS_FULFILLED = `${PREFIX}FETCH_USERS_FULFILLED`;
export const FETCH_USERS_REJECTED = `${PREFIX}FETCH_USERS_REJECTED`;

export const FETCH_USER_REQUEST = `${PREFIX}FETCH_USER_REQUEST`;
export const FETCH_USER_FULFILLED = `${PREFIX}FETCH_USER_FULFILLED`;
export const FETCH_USER_REJECTED = `${PREFIX}FETCH_USER_REJECTED`;

export const CREATE_USER_REQUEST = `${PREFIX}CREATE_USER_REQUEST`;
export const CREATE_USER_FULFILLED = `${PREFIX}CREATE_USER_FULFILLED`;
export const CREATE_USER_REJECTED = `${PREFIX}CREATE_USER_REJECTED`;

export const UPDATE_USER_REQUEST = `${PREFIX}UPDATE_USER_REQUEST`;
export const UPDATE_USER_FULFILLED = `${PREFIX}UPDATE_USER_FULFILLED`;
export const UPDATE_USER_REJECTED = `${PREFIX}UPDATE_USER_REJECTED`;

export const DELETE_USERS_REQUEST = `${PREFIX}DELETE_USERS_REQUEST`;
export const DELETE_USER_REQUEST = `${PREFIX}DELETE_USER_REQUEST`;
export const DELETE_USER_FULFILLED = `${PREFIX}DELETE_USER_FULFILLED`;
export const DELETE_USER_REJECTED = `${PREFIX}DELETE_USER_REJECTED`;

export const UNLOAD_USERS = `${PREFIX}UNLOAD_USERS`;
export const UNLOAD_USER = `${PREFIX}UNLOAD_USER`;

/**
 * Groups
 */
export const FETCH_GROUPS_REQUEST = `${PREFIX}FETCH_GROUPS_REQUEST`;
export const FETCH_GROUPS_FULFILLED = `${PREFIX}FETCH_GROUPS_FULFILLED`;
export const FETCH_GROUPS_REJECTED = `${PREFIX}FETCH_GROUPS_REJECTED`;

export const FETCH_GROUP_REQUEST = `${PREFIX}FETCH_GROUP_REQUEST`;
export const FETCH_GROUP_FULFILLED = `${PREFIX}FETCH_GROUP_FULFILLED`;
export const FETCH_GROUP_REJECTED = `${PREFIX}FETCH_GROUP_REJECTED`;

export const CREATE_GROUP_REQUEST = `${PREFIX}CREATE_GROUP_REQUEST`;
export const CREATE_GROUP_FULFILLED = `${PREFIX}CREATE_GROUP_FULFILLED`;
export const CREATE_GROUP_REJECTED = `${PREFIX}CREATE_GROUP_REJECTED`;

export const UPDATE_GROUP_REQUEST = `${PREFIX}UPDATE_GROUP_REQUEST`;
export const UPDATE_GROUP_FULFILLED = `${PREFIX}UPDATE_GROUP_FULFILLED`;
export const UPDATE_GROUP_REJECTED = `${PREFIX}UPDATE_GROUP_REJECTED`;

export const DELETE_GROUPS_REQUEST = `${PREFIX}DELETE_GROUPS_REQUEST`;
export const DELETE_GROUP_REQUEST = `${PREFIX}DELETE_GROUP_REQUEST`;
export const DELETE_GROUP_FULFILLED = `${PREFIX}DELETE_GROUP_FULFILLED`;
export const DELETE_GROUP_REJECTED = `${PREFIX}DELETE_GROUP_REJECTED`;

export const ADD_GROUP_MEMBER_REQUEST = `${PREFIX}ADD_GROUP_MEMBER_REQUEST`;
export const ADD_GROUP_MEMBER_FULFILLED = `${PREFIX}ADD_GROUP_MEMBER_FULFILLED`;
export const ADD_GROUP_MEMBER_REJECTED = `${PREFIX}ADD_GROUP_MEMBER_REJECTED`;
export const REMOVE_GROUP_MEMBER_REQUEST = `${PREFIX}REMOVE_GROUP_MEMBER_REQUEST`;
export const REMOVE_GROUP_MEMBER_FULFILLED = `${PREFIX}REMOVE_GROUP_MEMBER_FULFILLED`;
export const REMOVE_GROUP_MEMBER_REJECTED = `${PREFIX}REMOVE_GROUP_MEMBER_REJECTED`;

export const UNLOAD_GROUPS = `${PREFIX}UNLOAD_GROUPS`;
export const UNLOAD_GROUP = `${PREFIX}UNLOAD_GROUP`;

/**
 * Env
 */
export const FETCH_ENV_REQUEST = `${PREFIX}FETCH_ENV_REQUEST`;
export const FETCH_ENV_FULFILLED = `${PREFIX}FETCH_ENV_FULFILLED`;
export const FETCH_ENV_REJECTED = `${PREFIX}FETCH_ENV_REJECTED`;

export const FETCH_ENV_SCHEMA_REQUEST = `${PREFIX}FETCH_ENV_SCHEMA_REQUEST`;
export const FETCH_ENV_SCHEMA_FULFILLED = `${PREFIX}FETCH_ENV_SCHEMA_FULFILLED`;
export const FETCH_ENV_SCHEMA_REJECTED = `${PREFIX}FETCH_ENV_SCHEMA_REJECTED`;

export const UNLOAD_ENV_SCHEMA = `${PREFIX}UNLOAD_ENV_SCHEMA`;

/**
 * Logs
 */
export const FETCH_LOGPROVIDER_REQUEST = `${PREFIX}FETCH_LOGPROVIDER_REQUEST`;
export const FETCH_LOGPROVIDER_FULFILLED = `${PREFIX}FETCH_LOGPROVIDER_FULFILLED`;
export const FETCH_LOGPROVIDER_REJECTED = `${PREFIX}FETCH_LOGPROVIDER_REJECTED`;
export const UNLOAD_LOGPROVIDER = `${PREFIX}UNLOAD_LOGPROVIDER`;

/**
 * Search
 */
export const FETCH_SEARCH_REQUEST = `${PREFIX}FETCH_SEARCH_REQUEST`;
export const FETCH_SEARCH_FULFILLED = `${PREFIX}FETCH_SEARCH_FULFILLED`;
export const FETCH_SEARCH_REJECTED = `${PREFIX}FETCH_SEARCH_REJECTED`;
export const UNLOAD_SEARCH = `${PREFIX}UNLOAD_SEARCH`;

/**
 * Type Properties
 */
export const CREATE_TYPEPROPERTY_REQUEST = `${PREFIX}CREATE_TYPEPROPERTY_REQUEST`;
export const CREATE_TYPEPROPERTY_FULFILLED = `${PREFIX}CREATE_TYPEPROPERTY_FULFILLED`;
export const CREATE_TYPEPROPERTY_REJECTED = `${PREFIX}CREATE_TYPEPROPERTY_REJECTED`;
export const UPDATE_TYPEPROPERTY_REQUEST = `${PREFIX}UPDATE_TYPEPROPERTY_REQUEST`;
export const UPDATE_TYPEPROPERTY_FULFILLED = `${PREFIX}UPDATE_TYPEPROPERTY_FULFILLED`;
export const UPDATE_TYPEPROPERTY_REJECTED = `${PREFIX}UPDATE_TYPEPROPERTY_REJECTED`;
export const DELETE_TYPEPROPERTY_REQUEST = `${PREFIX}DELETE_TYPEPROPERTY_REQUEST`;
export const DELETE_TYPEPROPERTY_FULFILLED = `${PREFIX}DELETE_TYPEPROPERTY_FULFILLED`;
export const DELETE_TYPEPROPERTY_REJECTED = `${PREFIX}DELETE_TYPEPROPERTY_REJECTED`;
export const BATCH_UPDATE_TYPEPROPERTY_REQUEST = `${PREFIX}BATCH_UPDATE_TYPEPROPERTY_REQUEST`;
export const BATCH_UPDATE_TYPEPROPERTY_FULFILLED = `${PREFIX}BATCH_UPDATE_TYPEPROPERTY_FULFILLED`;
export const BATCH_UPDATE_TYPEPROPERTY_REJECTED = `${PREFIX}BATCH_UPDATE_TYPEPROPERTY_REJECTED`;
