/**
 * Actions for containment state management/switching. Typically, these are called when an org, workspace or
 * environment is navigated to.
 */
export const SET_CURRENT_ORG_CONTEXT_REQUEST = 'metaResource/SET_CURRENT_ORG_CONTEXT_REQUEST';
export const SET_CURRENT_ORG_CONTEXT_PENDING = 'metaResource/SET_CURRENT_ORG_CONTEXT_PENDING';
export const SET_CURRENT_ORG_CONTEXT_REJECTED = 'metaResource/SET_CURRENT_ORG_CONTEXT_REJECTED';

export const SET_CURRENT_WORKSPACE_CONTEXT_REQUEST = 'metaResource/SET_CURRENT_WORKSPACE_CONTEXT_REQUEST';
export const SET_CURRENT_WORKSPACE_CONTEXT_PENDING = 'metaResource/SET_CURRENT_WORKSPACE_CONTEXT_PENDING';
export const SET_CURRENT_WORKSPACE_CONTEXT_REJECTED = 'metaResource/SET_CURRENT_WORKSPACE_CONTEXT_REJECTED';

export const SET_CURRENT_ENVIRONMENT_CONTEXT_REQUEST = 'metaResource/SET_CURRENT_ENVIRONMENT_CONTEXT_REQUEST';
export const SET_CURRENT_ENVIRONMENT_CONTEXT_PENDING = 'metaResource/SET_CURRENT_ENVIRONMENT_CONTEXT_PENDING';
export const SET_CURRENT_ENVIRONMENT_CONTEXT_REJECTED = 'metaResource/SET_CURRENT_ENVIRONMENT_CONTEXT_REJECTED';

export const UPDATE_CURRENT_ORG_CONTEXT = 'metaResource/UPDATE_CURRENT_ORG_CONTEXT';
export const UPDATE_CURRENT_WORKSPACE_CONTEXT = 'metaResource/UPDATE_CURRENT_WORKSPACE_CONTEXT';
export const UPDATE_CURRENT_ENVIRONMENT_CONTEXT = 'metaResource/UPDATE_CURRENT_ENVIRONMENT_CONTEXT';

export const UNLOAD_CURRENT_WORKSPACE_CONTEXT = 'metaResource/UNLOAD_CURRENT_WORKSPACE_CONTEXT';
export const UNLOAD_CURRENT_ENVIRONMENT_CONTEXT = 'metaResource/UNLOAD_CURRENT_ENVIRONMENT_CONTEXT';

/**
 * API
 */
export const FETCH_ALLORGS_REQUEST = 'metaResource/FETCH_ALLORGS_REQUEST';
export const FETCH_ALLORGS_PENDING = 'metaResource/FETCH_ALLORGS_PENDING';
export const FETCH_ALLORGS_FULFILLED = 'metaResource/FETCH_ALLORGS_FULFILLED';
export const FETCH_ALLORGS_REJECTED = 'metaResource/FETCH_ALLORGS_REJECTED';

export const FETCH_ORGS_REQUEST = 'metaResource/FETCH_ORGS_REQUEST';
export const FETCH_ORGS_PENDING = 'metaResource/FETCH_ORGS_PENDING';
export const FETCH_ORGS_FULFILLED = 'metaResource/FETCH_ORGS_FULFILLED';
export const FETCH_ORGS_REJECTED = 'metaResource/FETCH_ORGS_REJECTED';

export const FETCH_ORG_REQUEST = 'metaResource/FETCH_ORG_REQUEST';
export const FETCH_ORG_PENDING = 'metaResource/FETCH_ORG_PENDING';
export const FETCH_ORG_FULFILLED = 'metaResource/FETCH_ORG_FULFILLED';
export const FETCH_ORG_REJECTED = 'metaResource/FETCH_ORG_REJECTED';

export const FETCH_ORGSET_REQUEST = 'metaResource/FETCH_ORGSET_REQUEST';
export const FETCH_ORGSET_PENDING = 'metaResource/FETCH_ORGSET_PENDING';
export const FETCH_ORGSET_FULFILLED = 'metaResource/FETCH_ORGSET_FULFILLED';
export const FETCH_ORGSET_REJECTED = 'metaResource/FETCH_ORGSET_REJECTED';

export const CREATE_ORG_REQUEST = 'metaResource/CREATE_ORG_REQUEST';
export const CREATE_ORG_PENDING = 'metaResource/CREATE_ORG_PENDING';
export const CREATE_ORG_FULFILLED = 'metaResource/CREATE_ORG_FULFILLED';
export const CREATE_ORG_REJECTED = 'metaResource/CREATE_ORG_REJECTED';

export const UPDATE_ORG_REQUEST = 'metaResource/UPDATE_ORG_REQUEST';
export const UPDATE_ORG_PENDING = 'metaResource/UPDATE_ORG_PENDING';
export const UPDATE_ORG_FULFILLED = 'metaResource/UPDATE_ORG_FULFILLED';
export const UPDATE_ORG_REJECTED = 'metaResource/UPDATE_ORG_REJECTED';

export const DELETE_ORG_REQUEST = 'metaResource/DELETE_ORG_REQUEST';
export const DELETE_ORG_PENDING = 'metaResource/DELETE_ORG_PENDING';
export const DELETE_ORG_FULFILLED = 'metaResource/DELETE_ORG_FULFILLED';
export const DELETE_ORG_REJECTED = 'metaResource/DELETE_ORG_REJECTED';

export const FETCH_WORKSPACES_REQUEST = 'metaResource/FETCH_WORKSPACES_REQUEST';
export const FETCH_WORKSPACES_PENDING = 'metaResource/FETCH_WORKSPACES_PENDING';
export const FETCH_WORKSPACES_FULFILLED = 'metaResource/FETCH_WORKSPACES_FULFILLED';
export const FETCH_WORKSPACES_REJECTED = 'metaResource/FETCH_WORKSPACES_REJECTED';

export const FETCH_WORKSPACE_REQUEST = 'metaResource/FETCH_WORKSPACE_REQUEST';
export const FETCH_WORKSPACE_PENDING = 'metaResource/FETCH_WORKSPACE_PENDING';
export const FETCH_WORKSPACE_FULFILLED = 'metaResource/FETCH_WORKSPACE_FULFILLED';
export const FETCH_WORKSPACE_REJECTED = 'metaResource/FETCH_WORKSPACE_REJECTED';

export const FETCH_ENVIRONMENTS_REQUEST = 'metaResource/FETCH_ENVIRONMENTS_REQUEST';
export const FETCH_ENVIRONMENTS_PENDING = 'metaResource/FETCH_ENVIRONMENTS_PENDING';
export const FETCH_ENVIRONMENTS_FULFILLED = 'metaResource/FETCH_ENVIRONMENTS_FULFILLED';
export const FETCH_ENVIRONMENTS_REJECTED = 'metaResource/FETCH_ENVIRONMENTS_REJECTED';

export const FETCH_ENVIRONMENT_REQUEST = 'metaResource/FETCH_ENVIRONMENT_REQUEST';
export const FETCH_ENVIRONMENT_PENDING = 'metaResource/FETCH_ENVIRONMENT_PENDING';
export const FETCH_ENVIRONMENT_FULFILLED = 'metaResource/FETCH_ENVIRONMENT_FULFILLED';
export const FETCH_ENVIRONMENT_REJECTED = 'metaResource/FETCH_ENVIRONMENT_REJECTED';

export const FETCH_SELF_REQUEST = 'metaResource/FETCH_SELF_REQUEST';
export const FETCH_SELF_PENDING = 'metaResource/FETCH_SELF_PENDING';
export const FETCH_SELF_FULFILLED = 'metaResource/FETCH_SELF_FULFILLED';
export const FETCH_SELF_REJECTED = 'metaResource/FETCH_SELF_REJECTED';
