export const PREFIX = 'metaResource/';

/**
 * Orgs
 */
export const FETCH_ALLORGS_REQUEST = `${PREFIX}FETCH_ALLORGS_REQUEST`;
export const FETCH_ALLORGS_FULFILLED = `${PREFIX}FETCH_ALLORGS_FULFILLED`;
export const FETCH_ALLORGS_REJECTED = `${PREFIX}FETCH_ALLORGS_REJECTED`;

export const FETCH_ALLORGS_DROPDOWN_REQUEST = `${PREFIX}FETCH_ALLORGS_DROPDOWN_REQUEST`;
export const FETCH_ALLORGS_DROPDOWN_FULFILLED = `${PREFIX}FETCH_ALLORGS_DROPDOWN_FULFILLED`;
export const FETCH_ALLORGS_DROPDOWN_REJECTED = `${PREFIX}FETCH_ALLORGS_DROPDOWN_REJECTED`;

export const FETCH_ORGS_REQUEST = `${PREFIX}FETCH_ORGS_REQUEST`;
export const FETCH_ORGS_FULFILLED = `${PREFIX}FETCH_ORGS_FULFILLED`;
export const FETCH_ORGS_REJECTED = `${PREFIX}FETCH_ORGS_REJECTED`;

export const FETCH_ORG_REQUEST = `${PREFIX}FETCH_ORG_REQUEST`;
export const FETCH_ORG_FULFILLED = `${PREFIX}FETCH_ORG_FULFILLED`;
export const FETCH_ORG_REJECTED = `${PREFIX}FETCH_ORG_REJECTED`;

export const FETCH_ORGSET_REQUEST = `${PREFIX}FETCH_ORGSET_REQUEST`;
export const FETCH_ORGSET_FULFILLED = `${PREFIX}FETCH_ORGSET_FULFILLED`;
export const FETCH_ORGSET_REJECTED = `${PREFIX}FETCH_ORGSET_REJECTED`;

export const CREATE_ORG_REQUEST = `${PREFIX}CREATE_ORG_REQUEST`;
export const CREATE_ORG_FULFILLED = `${PREFIX}CREATE_ORG_FULFILLED`;
export const CREATE_ORG_REJECTED = `${PREFIX}CREATE_ORG_REJECTED`;

export const UPDATE_ORG_REQUEST = `${PREFIX}UPDATE_ORG_REQUEST`;
export const UPDATE_ORG_FULFILLED = `${PREFIX}UPDATE_ORG_FULFILLED`;
export const UPDATE_ORG_REJECTED = `${PREFIX}UPDATE_ORG_REJECTED`;

export const DELETE_ORG_REQUEST = `${PREFIX}DELETE_ORG_REQUEST`;
export const DELETE_ORG_FULFILLED = `${PREFIX}DELETE_ORG_FULFILLED`;
export const DELETE_ORG_REJECTED = `${PREFIX}DELETE_ORG_REJECTED`;

export const UNLOAD_ALLORGS = `${PREFIX}UNLOAD_ALLORGS`;
export const UNLOAD_ORGSET = `${PREFIX}UNLOAD_ORGSET`;
export const UNLOAD_ORGANIZATION = `${PREFIX}UNLOAD_ORGANIZATION`;

/**
 * Workspaces
 */
export const FETCH_WORKSPACES_REQUEST = `${PREFIX}FETCH_WORKSPACES_REQUEST`;
export const FETCH_WORKSPACES_FULFILLED = `${PREFIX}FETCH_WORKSPACES_FULFILLED`;
export const FETCH_WORKSPACES_REJECTED = `${PREFIX}FETCH_WORKSPACES_REJECTED`;

export const FETCH_WORKSPACE_REQUEST = `${PREFIX}FETCH_WORKSPACE_REQUEST`;
export const FETCH_WORKSPACE_FULFILLED = `${PREFIX}FETCH_WORKSPACE_FULFILLED`;
export const FETCH_WORKSPACE_REJECTED = `${PREFIX}FETCH_WORKSPACE_REJECTED`;

export const CREATE_WORKSPACE_REQUEST = `${PREFIX}CREATE_WORKSPACE_REQUEST`;
export const CREATE_WORKSPACE_FULFILLED = `${PREFIX}CREATE_WORKSPACE_FULFILLED`;
export const CREATE_WORKSPACE_REJECTED = `${PREFIX}CREATE_WORKSPACE_REJECTED`;

export const UPDATE_WORKSPACE_REQUEST = `${PREFIX}UPDATE_WORKSPACE_REQUEST`;
export const UPDATE_WORKSPACE_FULFILLED = `${PREFIX}UPDATE_WORKSPACE_FULFILLED`;
export const UPDATE_WORKSPACE_REJECTED = `${PREFIX}UPDATE_WORKSPACE_REJECTED`;

export const DELETE_WORKSPACE_REQUEST = `${PREFIX}DELETE_WORKSPACE_REQUEST`;
export const DELETE_WORKSPACE_FULFILLED = `${PREFIX}DELETE_WORKSPACE_FULFILLED`;
export const DELETE_WORKSPACE_REJECTED = `${PREFIX}DELETE_WORKSPACE_REJECTED`;

export const UNLOAD_WORKSPACES = `${PREFIX}UNLOAD_WORKSPACES`;
export const UNLOAD_WORKSPACE = `${PREFIX}UNLOAD_WORKSPACE`;

/**
 * Environments
 */
export const FETCH_ENVIRONMENTS_REQUEST = `${PREFIX}FETCH_ENVIRONMENTS_REQUEST`;
export const FETCH_ENVIRONMENTS_FULFILLED = `${PREFIX}FETCH_ENVIRONMENTS_FULFILLED`;
export const FETCH_ENVIRONMENTS_REJECTED = `${PREFIX}FETCH_ENVIRONMENTS_REJECTED`;

export const FETCH_ENVIRONMENT_REQUEST = `${PREFIX}FETCH_ENVIRONMENT_REQUEST`;
export const FETCH_ENVIRONMENT_FULFILLED = `${PREFIX}FETCH_ENVIRONMENT_FULFILLED`;
export const FETCH_ENVIRONMENT_REJECTED = `${PREFIX}FETCH_ENVIRONMENT_REJECTED`;

export const CREATE_ENVIRONMENT_REQUEST = `${PREFIX}CREATE_ENVIRONMENT_REQUEST`;
export const CREATE_ENVIRONMENT_FULFILLED = `${PREFIX}CREATE_ENVIRONMENT_FULFILLED`;
export const CREATE_ENVIRONMENT_REJECTED = `${PREFIX}CREATE_ENVIRONMENT_REJECTED`;

export const UPDATE_ENVIRONMENT_REQUEST = `${PREFIX}UPDATE_ENVIRONMENT_REQUEST`;
export const UPDATE_ENVIRONMENT_FULFILLED = `${PREFIX}UPDATE_ENVIRONMENT_FULFILLED`;
export const UPDATE_ENVIRONMENT_REJECTED = `${PREFIX}UPDATE_ENVIRONMENT_REJECTED`;

export const DELETE_ENVIRONMENT_REQUEST = `${PREFIX}DELETE_ENVIRONMENT_REQUEST`;
export const DELETE_ENVIRONMENT_FULFILLED = `${PREFIX}DELETE_ENVIRONMENT_FULFILLED`;
export const DELETE_ENVIRONMENT_REJECTED = `${PREFIX}DELETE_ENVIRONMENT_REJECTED`;

export const UNLOAD_ENVIRONMENTS = `${PREFIX}UNLOAD_ENVIRONMENTS`;
export const UNLOAD_ENVIRONMENT = `${PREFIX}UNLOAD_ENVIRONMENT`;

/**
 * Self
 */
export const FETCH_SELF_REQUEST = `${PREFIX}FETCH_SELF_REQUEST`;
export const FETCH_SELF_FULFILLED = `${PREFIX}FETCH_SELF_FULFILLED`;
export const FETCH_SELF_REJECTED = `${PREFIX}FETCH_SELF_REJECTED`;

/**
 * Lambdas
 */
export const FETCH_LAMBDAS_REQUEST = `${PREFIX}FETCH_LAMBDAS_REQUEST`;
export const FETCH_LAMBDAS_FULFILLED = `${PREFIX}FETCH_LAMBDAS_FULFILLED`;
export const FETCH_LAMBDAS_REJECTED = `${PREFIX}FETCH_LAMBDAS_REJECTED`;

export const FETCH_LAMBDA_REQUEST = `${PREFIX}FETCH_LAMBDA_REQUEST`;
export const FETCH_LAMBDA_FULFILLED = `${PREFIX}FETCH_LAMBDA_FULFILLED`;
export const FETCH_LAMBDA_REJECTED = `${PREFIX}FETCH_LAMBDA_REJECTED`;

export const CREATE_LAMBDA_REQUEST = `${PREFIX}CREATE_LAMBDA_REQUEST`;
export const CREATE_LAMBDA_FULFILLED = `${PREFIX}CREATE_LAMBDA_FULFILLED`;
export const CREATE_LAMBDA_REJECTED = `${PREFIX}CREATE_LAMBDA_REJECTED`;

export const UPDATE_LAMBDA_REQUEST = `${PREFIX}UPDATE_LAMBDA_REQUEST`;
export const UPDATE_LAMBDA_FULFILLED = `${PREFIX}UPDATE_LAMBDA_FULFILLED`;
export const UPDATE_LAMBDA_REJECTED = `${PREFIX}UPDATE_LAMBDA_REJECTED`;

export const DELETE_LAMBDAS_REQUEST = `${PREFIX}DELETE_LAMBDAS_REQUEST`;
export const DELETE_LAMBDA_REQUEST = `${PREFIX}DELETE_LAMBDA_REQUEST`;
export const DELETE_LAMBDA_FULFILLED = `${PREFIX}DELETE_LAMBDA_FULFILLED`;
export const DELETE_LAMBDA_REJECTED = `${PREFIX}DELETE_LAMBDA_REJECTED`;

export const FETCH_LAMBDA_PROVIDER_REQUEST = `${PREFIX}FETCH_LAMBDA_PROVIDER_REQUEST`;
export const FETCH_LAMBDA_PROVIDER_FULFILLED = `${PREFIX}FETCH_LAMBDA_PROVIDER_FULFILLED`;
export const FETCH_LAMBDA_PROVIDER_REJECTED = `${PREFIX}FETCH_LAMBDA_PROVIDER_REJECTED`;

export const FETCH_LAMBDAS_DROPDOWN_REQUEST = `${PREFIX}FETCH_LAMBDAS_DROPDOWN_REQUEST`;
export const FETCH_LAMBDAS_DROPDOWN_FULFILLED = `${PREFIX}FETCH_LAMBDAS_DROPDOWN_FULFILLED`;
export const FETCH_LAMBDAS_DROPDOWN_REJECTED = `${PREFIX}FETCH_LAMBDAS_DROPDOWN_REJECTED`;

export const UNLOAD_LAMBDAS = `${PREFIX}UNLOAD_LAMBDAS`;
export const UNLOAD_LAMBDA = `${PREFIX}UNLOAD_LAMBDA`;

/**
 * APIS
 */
export const FETCH_APIS_REQUEST = `${PREFIX}FETCH_APIS_REQUEST`;
export const FETCH_APIS_FULFILLED = `${PREFIX}FETCH_APIS_FULFILLED`;
export const FETCH_APIS_REJECTED = `${PREFIX}FETCH_APIS_REJECTED`;

export const FETCH_API_REQUEST = `${PREFIX}FETCH_API_REQUEST`;
export const FETCH_API_FULFILLED = `${PREFIX}FETCH_API_FULFILLED`;
export const FETCH_API_REJECTED = `${PREFIX}FETCH_API_REJECTED`;

export const CREATE_API_REQUEST = `${PREFIX}CREATE_API_REQUEST`;
export const CREATE_API_FULFILLED = `${PREFIX}CREATE_API_FULFILLED`;
export const CREATE_API_REJECTED = `${PREFIX}CREATE_API_REJECTED`;

export const UPDATE_API_REQUEST = `${PREFIX}UPDATE_API_REQUEST`;
export const UPDATE_API_FULFILLED = `${PREFIX}UPDATE_API_FULFILLED`;
export const UPDATE_API_REJECTED = `${PREFIX}UPDATE_API_REJECTED`;

export const DELETE_APIS_REQUEST = `${PREFIX}DELETE_APIS_REQUEST`;
export const DELETE_API_REQUEST = `${PREFIX}DELETE_API_REQUEST`;
export const DELETE_API_FULFILLED = `${PREFIX}DELETE_API_FULFILLED`;
export const DELETE_API_REJECTED = `${PREFIX}DELETE_API_REJECTED`;

export const UNLOAD_APIS = `${PREFIX}UNLOAD_APIS`;
export const UNLOAD_API = `${PREFIX}UNLOAD_API`;

/**
 * API Endpoints
 */
export const FETCH_APIENDPOINTS_REQUEST = `${PREFIX}FETCH_APIENDPOINTS_REQUEST`;
export const FETCH_APIENDPOINTS_FULFILLED = `${PREFIX}FETCH_APIENDPOINTS_FULFILLED`;
export const FETCH_APIENDPOINTS_REJECTED = `${PREFIX}FETCH_APIENDPOINTS_REJECTED`;

export const FETCH_APIENDPOINT_REQUEST = `${PREFIX}FETCH_APIENDPOINT_REQUEST`;
export const FETCH_APIENDPOINT_FULFILLED = `${PREFIX}FETCH_APIENDPOINT_FULFILLED`;
export const FETCH_APIENDPOINT_REJECTED = `${PREFIX}FETCH_APIENDPOINT_REJECTED`;

export const CREATE_APIENDPOINT_REQUEST = `${PREFIX}CREATE_APIENDPOINT_REQUEST`;
export const CREATE_APIENDPOINT_FULFILLED = `${PREFIX}CREATE_APIENDPOINT_FULFILLED`;
export const CREATE_APIENDPOINT_REJECTED = `${PREFIX}CREATE_APIENDPOINT_REJECTED`;

export const UPDATE_APIENDPOINT_REQUEST = `${PREFIX}UPDATE_APIENDPOINT_REQUEST`;
export const UPDATE_APIENDPOINT_FULFILLED = `${PREFIX}UPDATE_APIENDPOINT_FULFILLED`;
export const UPDATE_APIENDPOINT_REJECTED = `${PREFIX}UPDATE_APIENDPOINT_REJECTED`;

export const DELETE_APIENDPOINTS_REQUEST = `${PREFIX}DELETE_APIENDPOINTS_REQUEST`;
export const DELETE_APIENDPOINTS_FULFILLED = `${PREFIX}DELETE_APIENDPOINTS_FULFILLED`;
export const DELETE_APIENDPOINTS_REJECTED = `${PREFIX}DELETE_APIENDPOINTS_REJECTED`;

export const DELETE_APIENDPOINT_REQUEST = `${PREFIX}DELETE_APIENDPOINT_REQUEST`;
export const DELETE_APIENDPOINT_FULFILLED = `${PREFIX}DELETE_APIENDPOINT_FULFILLED`;
export const DELETE_APIENDPOINT_REJECTED = `${PREFIX}DELETE_APIENDPOINT_REJECTED`;

export const UNLOAD_APIENDPOINTS = `${PREFIX}UNLOAD_APIENDPOINTS`;
export const UNLOAD_APIENDPOINT = `${PREFIX}UNLOAD_APIENDPOINT`;

/**
 * Providers
 */
export const FETCH_PROVIDERS_REQUEST = `${PREFIX}FETCH_PROVIDERS_REQUEST`;
export const FETCH_PROVIDERS_FULFILLED = `${PREFIX}FETCH_PROVIDERS_FULFILLED`;
export const FETCH_PROVIDERS_REJECTED = `${PREFIX}FETCH_PROVIDERS_REJECTED`;

export const FETCH_PROVIDER_REQUEST = `${PREFIX}FETCH_PROVIDER_REQUEST`;
export const FETCH_PROVIDER_FULFILLED = `${PREFIX}FETCH_PROVIDER_FULFILLED`;
export const FETCH_PROVIDER_REJECTED = `${PREFIX}FETCH_PROVIDER_REJECTED`;

export const CREATE_PROVIDER_REQUEST = `${PREFIX}CREATE_PROVIDER_REQUEST`;
export const CREATE_PROVIDER_FULFILLED = `${PREFIX}CREATE_PROVIDER_FULFILLED`;
export const CREATE_PROVIDER_REJECTED = `${PREFIX}CREATE_PROVIDER_REJECTED`;

export const UPDATE_PROVIDER_REQUEST = `${PREFIX}UPDATE_PROVIDER_REQUEST`;
export const UPDATE_PROVIDER_FULFILLED = `${PREFIX}UPDATE_PROVIDER_FULFILLED`;
export const UPDATE_PROVIDER_REJECTED = `${PREFIX}UPDATE_PROVIDER_REJECTED`;

export const DELETE_PROVIDERS_REQUEST = `${PREFIX}DELETE_PROVIDERS_REQUEST`;
export const DELETE_PROVIDERS_FULFILLED = `${PREFIX}DELETE_PROVIDERS_FULFILLED`;
export const DELETE_PROVIDERS_REJECTED = `${PREFIX}DELETE_PROVIDERS_REJECTED`;

export const DELETE_PROVIDER_REQUEST = `${PREFIX}DELETE_PROVIDER_REQUEST`;
export const DELETE_PROVIDER_FULFILLED = `${PREFIX}DELETE_PROVIDER_FULFILLED`;
export const DELETE_PROVIDER_REJECTED = `${PREFIX}DELETE_PROVIDER_REJECTED`;

export const FETCH_PROVIDERS_BYTYPE_REQUEST = `${PREFIX}FETCH_PROVIDERS_BYTYPE_REQUEST`;
export const FETCH_PROVIDERS_BYTYPE_FULFILLED = `${PREFIX}FETCH_PROVIDERS_BYTYPE_FULFILLED`;
export const FETCH_PROVIDERS_BYTYPE_REJECTED = `${PREFIX}FETCH_PROVIDERS_BYTYPE_REJECTED`;

export const FETCH_PROVIDERS_KONG_GATEWAY_REQUEST = `${PREFIX}FETCH_PROVIDERS_KONG_GATEWAY_REQUEST`;
export const FETCH_PROVIDERS_KONG_GATEWAY_FULFILLED = `${PREFIX}FETCH_PROVIDERS_KONG_GATEWAY_FULFILLED`;
export const FETCH_PROVIDERS_KONG_GATEWAY_REJECTED = `${PREFIX}FETCH_PROVIDERS_KONG_GATEWAY_REJECTED`;

export const FETCH_EXECUTORS_REQUEST = `${PREFIX}FETCH_EXECUTORS_REQUEST`;
export const FETCH_EXECUTORS_FULFILLED = `${PREFIX}FETCH_EXECUTORS_FULFILLED`;
export const FETCH_EXECUTORS_REJECTED = `${PREFIX}FETCH_EXECUTORS_REJECTED`;

export const REDEPLOY_PROVIDER_REQUEST = `${PREFIX}REDEPLOY_PROVIDER_REQUEST`;
export const REDEPLOY_PROVIDER_FULFILLED = `${PREFIX}REDEPLOY_PROVIDER_FULFILLED`;
export const REDEPLOY_PROVIDER_REJECTED = `${PREFIX}REDEPLOY_PROVIDER_REJECTED`;

export const UNLOAD_PROVIDERS = `${PREFIX}UNLOAD_PROVIDERS`;
export const UNLOAD_PROVIDER = `${PREFIX}UNLOAD_PROVIDER`;

/**
 * Containers
 */
export const FETCH_CONTAINERS_REQUEST = `${PREFIX}FETCH_CONTAINERS_REQUEST`;
export const FETCH_CONTAINERS_FULFILLED = `${PREFIX}FETCH_CONTAINERS_FULFILLED`;
export const FETCH_CONTAINERS_REJECTED = `${PREFIX}FETCH_CONTAINERS_REJECTED`;

export const FETCH_CONTAINER_REQUEST = `${PREFIX}FETCH_CONTAINER_REQUEST`;
export const FETCH_CONTAINER_FULFILLED = `${PREFIX}FETCH_CONTAINER_FULFILLED`;
export const FETCH_CONTAINER_REJECTED = `${PREFIX}FETCH_CONTAINER_REJECTED`;

export const FETCH_PROVIDER_CONTAINER_REQUEST = `${PREFIX}FETCH_PROVIDER_CONTAINER_REQUEST`;
export const CREATE_CONTAINER_REQUEST = `${PREFIX}CREATE_CONTAINER_REQUEST`;
export const CREATE_CONTAINER_FULFILLED = `${PREFIX}CREATE_CONTAINER_FULFILLED`;
export const CREATE_CONTAINER_REJECTED = `${PREFIX}CREATE_CONTAINER_REJECTED`;

export const UPDATE_CONTAINER_REQUEST = `${PREFIX}UPDATE_CONTAINER_REQUEST`;
export const UPDATE_CONTAINER_FULFILLED = `${PREFIX}UPDATE_CONTAINER_FULFILLED`;
export const UPDATE_CONTAINER_REJECTED = `${PREFIX}UPDATE_CONTAINER_REJECTED`;

export const DELETE_CONTAINER_REQUEST = `${PREFIX}DELETE_CONTAINER_REQUEST`;
export const DELETE_CONTAINER_FULFILLED = `${PREFIX}DELETE_CONTAINER_FULFILLED`;
export const DELETE_CONTAINER_REJECTED = `${PREFIX}DELETE_CONTAINER_REJECTED`;

export const SCALE_CONTAINER_REQUEST = `${PREFIX}SCALE_CONTAINER_REQUEST`;
export const SCALE_CONTAINER_FULFILLED = `${PREFIX}SCALE_CONTAINER_FULFILLED`;
export const SCALE_CONTAINER_REJECTED = `${PREFIX}SCALE_CONTAINER_REJECTED`;

export const MIGRATE_CONTAINER_REQUEST = `${PREFIX}MIGRATE_CONTAINER_REQUEST`;
export const MIGRATE_CONTAINER_FULFILLED = `${PREFIX}MIGRATE_CONTAINER_FULFILLED`;
export const MIGRATE_CONTAINER_REJECTED = `${PREFIX}MIGRATE_CONTAINER_REJECTED`;

export const PROMOTE_CONTAINER_REQUEST = `${PREFIX}PROMOTE_CONTAINER_REQUEST`;
export const PROMOTE_CONTAINER_FULFILLED = `${PREFIX}PROMOTE_CONTAINER_FULFILLED`;
export const PROMOTE_CONTAINER_REJECTED = `${PREFIX}PROMOTE_CONTAINER_REJECTED`;

export const FETCH_CONTAINERS_DROPDOWN_REQUEST = `${PREFIX}FETCH_CONTAINERS_DROPDOWN_REQUEST`;
export const FETCH_CONTAINERS_DROPDOWN_FULFILLED = `${PREFIX}FETCH_CONTAINERS_DROPDOWN_FULFILLED`;
export const FETCH_CONTAINERS_DROPDOWN_REJECTED = `${PREFIX}FETCH_CONTAINERS_DROPDOWN_REJECTED`;

export const UNLOAD_CONTAINERS = `${PREFIX}UNLOAD_CONTAINERS`;
export const UNLOAD_CONTAINER = `${PREFIX}UNLOAD_CONTAINER`;

/**
 * Policies
 */
export const FETCH_POLICIES_REQUEST = `${PREFIX}FETCH_POLICIES_REQUEST`;
export const FETCH_POLICIES_FULFILLED = `${PREFIX}FETCH_POLICIES_FULFILLED`;
export const FETCH_POLICIES_REJECTED = `${PREFIX}FETCH_POLICIES_REJECTED`;

export const FETCH_POLICY_REQUEST = `${PREFIX}FETCH_POLICY_REQUEST`;
export const FETCH_POLICY_FULFILLED = `${PREFIX}FETCH_POLICY_FULFILLED`;
export const FETCH_POLICY_REJECTED = `${PREFIX}FETCH_POLICY_REJECTED`;

export const CREATE_POLICY_REQUEST = `${PREFIX}CREATE_POLICY_REQUEST`;
export const CREATE_POLICY_FULFILLED = `${PREFIX}CREATE_POLICY_FULFILLED`;
export const CREATE_POLICY_REJECTED = `${PREFIX}CREATE_POLICY_REJECTED`;

export const UPDATE_POLICY_REQUEST = `${PREFIX}UPDATE_POLICY_REQUEST`;
export const UPDATE_POLICY_FULFILLED = `${PREFIX}UPDATE_POLICY_FULFILLED`;
export const UPDATE_POLICY_REJECTED = `${PREFIX}UPDATE_POLICY_REJECTED`;

export const DELETE_POLICIES_REQUEST = `${PREFIX}DELETE_POLICIES_REQUEST`;
export const DELETE_POLICY_REQUEST = `${PREFIX}DELETE_POLICY_REQUEST`;
export const DELETE_POLICY_FULFILLED = `${PREFIX}DELETE_POLICY_FULFILLED`;
export const DELETE_POLICY_REJECTED = `${PREFIX}DELETE_POLICY_REJECTED`;

export const UNLOAD_POLICIES = `${PREFIX}UNLOAD_POLICIES`;
export const UNLOAD_POLICY = `${PREFIX}UNLOAD_POLICY`;

/**
 * Policy Rules
 */
export const FETCH_POLICYRULES_REQUEST = `${PREFIX}FETCH_POLICYRULES_REQUEST`;
export const FETCH_POLICYRULES_FULFILLED = `${PREFIX}FETCH_POLICYRULES_FULFILLED`;
export const FETCH_POLICYRULES_REJECTED = `${PREFIX}FETCH_POLICYRULES_REJECTED`;

export const FETCH_POLICYRULE_REQUEST = `${PREFIX}FETCH_POLICYRULE_REQUEST`;
export const FETCH_POLICYRULE_FULFILLED = `${PREFIX}FETCH_POLICYRULE_FULFILLED`;
export const FETCH_POLICYRULE_REJECTED = `${PREFIX}FETCH_POLICYRULE_REJECTED`;

export const CREATE_POLICYRULE_REQUEST = `${PREFIX}CREATE_POLICYRULE_REQUEST`;
export const CREATE_POLICYRULE_FULFILLED = `${PREFIX}CREATE_POLICYRULE_FULFILLED`;
export const CREATE_POLICYRULE_REJECTED = `${PREFIX}CREATE_POLICYRULE_REJECTED`;

export const UPDATE_POLICYRULE_REQUEST = `${PREFIX}UPDATE_POLICYRULE_REQUEST`;
export const UPDATE_POLICYRULE_FULFILLED = `${PREFIX}UPDATE_POLICYRULE_FULFILLED`;
export const UPDATE_POLICYRULE_REJECTED = `${PREFIX}UPDATE_POLICYRULE_REJECTED`;

export const DELETE_POLICYRULES_REQUEST = `${PREFIX}DELETE_POLICYRULES_REQUEST`;
export const DELETE_POLICYRULE_REQUEST = `${PREFIX}DELETE_POLICYRULE_REQUEST`;
export const DELETE_POLICYRULE_FULFILLED = `${PREFIX}DELETE_POLICYRULE_FULFILLED`;
export const DELETE_POLICYRULE_REJECTED = `${PREFIX}DELETE_POLICYRULE_REJECTED`;

export const UNLOAD_POLICYRULES = `${PREFIX}UNLOAD_POLICYRULES`;
export const UNLOAD_POLICYRULE = `${PREFIX}UNLOAD_POLICYRULE`;

/**
 * Entitlements
 */
export const FETCH_ENTITLEMENTS_REQUEST = `${PREFIX}FETCH_ENTITLEMENTS_REQUEST`;
export const FETCH_ENTITLEMENTS_FULFILLED = `${PREFIX}FETCH_ENTITLEMENTS_FULFILLED`;
export const FETCH_ENTITLEMENTS_REJECTED = `${PREFIX}FETCH_ENTITLEMENTS_REJECTED`;

export const FETCH_IDENTITIES_REQUEST = `${PREFIX}FETCH_IDENTITIES_REQUEST`;
export const FETCH_IDENTITIES_FULFILLED = `${PREFIX}FETCH_IDENTITIES_FULFILLED`;
export const FETCH_IDENTITIES_REJECTED = `${PREFIX}FETCH_IDENTITIES_REJECTED`;

export const UPDATE_ENTITLEMENT_REQUEST = `${PREFIX}UPDATE_ENTITLEMENT_REQUEST`;
export const UPDATE_ENTITLEMENT_FULFILLED = `${PREFIX}UPDATE_ENTITLEMENT_FULFILLED`;
export const UPDATE_ENTITLEMENT_REJECTED = `${PREFIX}UPDATE_ENTITLEMENT_REJECTED`;

export const UNLOAD_ENTITLEMENTS = `${PREFIX}UNLOAD_ENTITLEMENTS`;

/**
 * Users
 */
export const FETCH_USERS_REQUEST = `${PREFIX}FETCH_USERS_REQUEST`;
export const FETCH_USERS_FULFILLED = `${PREFIX}FETCH_USERS_FULFILLED`;
export const FETCH_USERS_REJECTED = `${PREFIX}FETCH_USERS_REJECTED`;

export const FETCH_USER_REQUEST = `${PREFIX}FETCH_USER_REQUEST`;
export const FETCH_USER_FULFILLED = `${PREFIX}FETCH_USER_FULFILLED`;
export const FETCH_USER_REJECTED = `${PREFIX}FETCH_USER_REJECTED`;

export const CREATE_USER_REQUEST = `${PREFIX}CREATE_USER_REQUEST`;
export const CREATE_USER_FULFILLED = `${PREFIX}CREATE_USER_FULFILLED`;
export const CREATE_USER_REJECTED = `${PREFIX}CREATE_USER_REJECTED`;

export const UPDATE_USER_REQUEST = `${PREFIX}UPDATE_USER_REQUEST`;
export const UPDATE_USER_FULFILLED = `${PREFIX}UPDATE_USER_FULFILLED`;
export const UPDATE_USER_REJECTED = `${PREFIX}UPDATE_USER_REJECTED`;

export const DELETE_USERS_REQUEST = `${PREFIX}DELETE_USERS_REQUEST`;
export const DELETE_USER_REQUEST = `${PREFIX}DELETE_USER_REQUEST`;
export const DELETE_USER_FULFILLED = `${PREFIX}DELETE_USER_FULFILLED`;
export const DELETE_USER_REJECTED = `${PREFIX}DELETE_USER_REJECTED`;

export const UNLOAD_USERS = `${PREFIX}UNLOAD_USERS`;
export const UNLOAD_USER = `${PREFIX}UNLOAD_USER`;

/**
 * Groups
 */
export const FETCH_GROUPS_REQUEST = `${PREFIX}FETCH_GROUPS_REQUEST`;
export const FETCH_GROUPS_FULFILLED = `${PREFIX}FETCH_GROUPS_FULFILLED`;
export const FETCH_GROUPS_REJECTED = `${PREFIX}FETCH_GROUPS_REJECTED`;

export const FETCH_GROUP_REQUEST = `${PREFIX}FETCH_GROUP_REQUEST`;
export const FETCH_GROUP_FULFILLED = `${PREFIX}FETCH_GROUP_FULFILLED`;
export const FETCH_GROUP_REJECTED = `${PREFIX}FETCH_GROUP_REJECTED`;

export const CREATE_GROUP_REQUEST = `${PREFIX}CREATE_GROUP_REQUEST`;
export const CREATE_GROUP_FULFILLED = `${PREFIX}CREATE_GROUP_FULFILLED`;
export const CREATE_GROUP_REJECTED = `${PREFIX}CREATE_GROUP_REJECTED`;

export const UPDATE_GROUP_REQUEST = `${PREFIX}UPDATE_GROUP_REQUEST`;
export const UPDATE_GROUP_FULFILLED = `${PREFIX}UPDATE_GROUP_FULFILLED`;
export const UPDATE_GROUP_REJECTED = `${PREFIX}UPDATE_GROUP_REJECTED`;

export const DELETE_GROUPS_REQUEST = `${PREFIX}DELETE_GROUPS_REQUEST`;
export const DELETE_GROUP_REQUEST = `${PREFIX}DELETE_GROUP_REQUEST`;
export const DELETE_GROUP_FULFILLED = `${PREFIX}DELETE_GROUP_FULFILLED`;
export const DELETE_GROUP_REJECTED = `${PREFIX}DELETE_GROUP_REJECTED`;

export const ADD_GROUP_MEMBER_REQUEST = `${PREFIX}ADD_GROUP_MEMBER_REQUEST`;
export const ADD_GROUP_MEMBER_FULFILLED = `${PREFIX}ADD_GROUP_MEMBER_FULFILLED`;
export const ADD_GROUP_MEMBER_REJECTED = `${PREFIX}ADD_GROUP_MEMBER_REJECTED`;
export const REMOVE_GROUP_MEMBER_REQUEST = `${PREFIX}REMOVE_GROUP_MEMBER_REQUEST`;
export const REMOVE_GROUP_MEMBER_FULFILLED = `${PREFIX}REMOVE_GROUP_MEMBER_FULFILLED`;
export const REMOVE_GROUP_MEMBER_REJECTED = `${PREFIX}REMOVE_GROUP_MEMBER_REJECTED`;

export const UNLOAD_GROUPS = `${PREFIX}UNLOAD_GROUPS`;
export const UNLOAD_GROUP = `${PREFIX}UNLOAD_GROUP`;

/**
 * Env
 */
export const FETCH_ENV_REQUEST = `${PREFIX}FETCH_ENV_REQUEST`;
export const FETCH_ENV_FULFILLED = `${PREFIX}FETCH_ENV_FULFILLED`;
export const FETCH_ENV_REJECTED = `${PREFIX}FETCH_ENV_REJECTED`;

export const FETCH_ENV_SCHEMA_REQUEST = `${PREFIX}FETCH_ENV_SCHEMA_REQUEST`;
export const FETCH_ENV_SCHEMA_FULFILLED = `${PREFIX}FETCH_ENV_SCHEMA_FULFILLED`;
export const FETCH_ENV_SCHEMA_REJECTED = `${PREFIX}FETCH_ENV_SCHEMA_REJECTED`;

export const UNLOAD_ENV_SCHEMA = `${PREFIX}UNLOAD_ENV_SCHEMA`;

/**
 * Logs
 */
export const FETCH_LOGPROVIDER_REQUEST = `${PREFIX}FETCH_LOGPROVIDER_REQUEST`;
export const FETCH_LOGPROVIDER_FULFILLED = `${PREFIX}FETCH_LOGPROVIDER_FULFILLED`;
export const FETCH_LOGPROVIDER_REJECTED = `${PREFIX}FETCH_LOGPROVIDER_REJECTED`;

/**
 * Actions
 */
export const FETCH_ACTIONS_REQUEST = `${PREFIX}FETCH_ACTIONS_REQUEST`;
export const FETCH_ACTIONS_FULFILLED = `${PREFIX}FETCH_ACTIONS_FULFILLED`;
export const FETCH_ACTIONS_REJECTED = `${PREFIX}FETCH_ACTIONS_REJECTED`;
export const UNLOAD_ACTIONS = `${PREFIX}UNLOAD_ACTIONS`;

export const FETCH_CONTEXT_ACTIONS_REQUEST = `${PREFIX}FETCH_CONTEXT_ACTIONS_REQUEST`;
export const FETCH_CONTEXT_ACTIONS_FULFILLED = `${PREFIX}FETCH_CONTEXT_ACTIONS_FULFILLED`;
export const FETCH_CONTEXT_ACTIONS_REJECTED = `${PREFIX}FETCH_CONTEXT_ACTIONS_REJECTED`;
export const UNLOAD_CONTEXT_ACTIONS = `${PREFIX}UNLOAD_CONTEXT_ACTIONS`;

/**
 * Secrets
 */
export const FETCH_SECRETS_REQUEST = `${PREFIX}FETCH_SECRETS_REQUEST`;
export const FETCH_SECRETS_FULFILLED = `${PREFIX}FETCH_SECRETS_FULFILLED`;
export const FETCH_SECRETS_REJECTED = `${PREFIX}FETCH_SECRETS_REJECTED`;

export const FETCH_SECRET_REQUEST = `${PREFIX}FETCH_SECRET_REQUEST`;
export const FETCH_SECRET_FULFILLED = `${PREFIX}FETCH_SECRET_FULFILLED`;
export const FETCH_SECRET_REJECTED = `${PREFIX}FETCH_SECRET_REJECTED`;

export const CREATE_SECRET_REQUEST = `${PREFIX}CREATE_SECRET_REQUEST`;
export const CREATE_SECRET_FULFILLED = `${PREFIX}CREATE_SECRET_FULFILLED`;
export const CREATE_SECRET_REJECTED = `${PREFIX}CREATE_SECRET_REJECTED`;

export const UPDATE_SECRET_REQUEST = `${PREFIX}UPDATE_SECRET_REQUEST`;
export const UPDATE_SECRET_FULFILLED = `${PREFIX}UPDATE_SECRET_FULFILLED`;
export const UPDATE_SECRET_REJECTED = `${PREFIX}UPDATE_SECRET_REJECTED`;

export const DELETE_SECRETS_REQUEST = `${PREFIX}DELETE_SECRETS_REQUEST`;
export const DELETE_SECRETS_FULFILLED = `${PREFIX}DELETE_SECRETS_FULFILLED`;
export const DELETE_SECRETS_REJECTED = `${PREFIX}DELETE_SECRETS_REJECTED`;
export const DELETE_SECRET_REQUEST = `${PREFIX}DELETE_SECRET_REQUEST`;
export const DELETE_SECRET_FULFILLED = `${PREFIX}DELETE_SECRET_FULFILLED`;
export const DELETE_SECRET_REJECTED = `${PREFIX}DELETE_SECRET_REJECTED`;

export const UNLOAD_SECRETS = `${PREFIX}UNLOAD_SECRETS`;
export const UNLOAD_SECRET = `${PREFIX}UNLOAD_SECRET`;

export const FETCH_SECRETS_DROPDOWN_REQUEST = `${PREFIX}FETCH_SECRETS_DROPDOWN_REQUEST`;
export const FETCH_SECRETS_DROPDOWN_FULFILLED = `${PREFIX}FETCH_SECRETS_DROPDOWN_FULFILLED`;
export const FETCH_SECRETS_DROPDOWN_REJECTED = `${PREFIX}FETCH_SECRETS_DROPDOWN_REJECTED`;

/**
 * Search
 */
export const FETCH_SEARCH_REQUEST = `${PREFIX}FETCH_SEARCH_REQUEST`;
export const FETCH_SEARCH_FULFILLED = `${PREFIX}FETCH_SEARCH_FULFILLED`;
export const FETCH_SEARCH_REJECTED = `${PREFIX}FETCH_SEARCH_REJECTED`;
export const UNLOAD_SEARCH = `${PREFIX}UNLOAD_SEARCH`;

/**
 * Resource Types
 */
export const FETCH_RESOURCETYPES_REQUEST = `${PREFIX}FETCH_RESOURCETYPES_REQUEST`;
export const FETCH_RESOURCETYPES_FULFILLED = `${PREFIX}FETCH_RESOURCETYPES_FULFILLED`;
export const FETCH_RESOURCETYPES_REJECTED = `${PREFIX}FETCH_RESOURCETYPES_REJECTED`;
export const FETCH_RESOURCETYPE_REQUEST = `${PREFIX}FETCH_RESOURCETYPE_REQUEST`;
export const FETCH_RESOURCETYPE_FULFILLED = `${PREFIX}FETCH_RESOURCETYPE_FULFILLED`;
export const FETCH_RESOURCETYPE_REJECTED = `${PREFIX}FETCH_RESOURCETYPE_REJECTED`;
export const CREATE_RESOURCETYPE_REQUEST = `${PREFIX}CREATE_RESOURCETYPE_REQUEST`;
export const CREATE_RESOURCETYPE_FULFILLED = `${PREFIX}CREATE_RESOURCETYPE_FULFILLED`;
export const CREATE_RESOURCETYPE_REJECTED = `${PREFIX}CREATE_RESOURCETYPE_REJECTED`;
export const DELETE_RESOURCETYPES_REQUEST = `${PREFIX}DELETE_RESOURCETYPES_REQUEST`;
export const UPDATE_RESOURCETYPE_REQUEST = `${PREFIX}UPDATE_RESOURCETYPE_REQUEST`;
export const UPDATE_RESOURCETYPE_FULFILLED = `${PREFIX}UPDATE_RESOURCETYPE_FULFILLED`;
export const UPDATE_RESOURCETYPE_REJECTED = `${PREFIX}UPDATE_RESOURCETYPE_REJECTED`;
export const DELETE_RESOURCETYPE_REQUEST = `${PREFIX}DELETE_RESOURCETYPE_REQUEST`;
export const DELETE_RESOURCETYPE_FULFILLED = `${PREFIX}DELETE_RESOURCETYPE_FULFILLED`;
export const DELETE_RESOURCETYPE_REJECTED = `${PREFIX}DELETE_RESOURCETYPE_REJECTED`;
export const UNLOAD_RESOURCETYPES = `${PREFIX}UNLOAD_RESOURCETYPES`;
export const UNLOAD_RESOURCETYPE = `${PREFIX}UNLOAD_RESOURCETYPE`;
export const FETCH_RESOURCETYPES_DROPDOWN_REQUEST = `${PREFIX}FETCH_RESOURCETYPES_DROPDOWN_REQUEST`;
export const FETCH_RESOURCETYPES_DROPDOWN_FULFILLED = `${PREFIX}FETCH_RESOURCETYPES_DROPDOWN_FULFILLED`;
export const FETCH_RESOURCETYPES_DROPDOWN_REJECTED = `${PREFIX}FETCH_RESOURCETYPES_DROPDOWN_REJECTED`;

/**
 * Type Properties
 */
export const CREATE_TYPEPROPERTY_REQUEST = `${PREFIX}CREATE_TYPEPROPERTY_REQUEST`;
export const CREATE_TYPEPROPERTY_FULFILLED = `${PREFIX}CREATE_TYPEPROPERTY_FULFILLED`;
export const CREATE_TYPEPROPERTY_REJECTED = `${PREFIX}CREATE_TYPEPROPERTY_REJECTED`;
export const UPDATE_TYPEPROPERTY_REQUEST = `${PREFIX}UPDATE_TYPEPROPERTY_REQUEST`;
export const UPDATE_TYPEPROPERTY_FULFILLED = `${PREFIX}UPDATE_TYPEPROPERTY_FULFILLED`;
export const UPDATE_TYPEPROPERTY_REJECTED = `${PREFIX}UPDATE_TYPEPROPERTY_REJECTED`;
export const DELETE_TYPEPROPERTY_REQUEST = `${PREFIX}DELETE_TYPEPROPERTY_REQUEST`;
export const DELETE_TYPEPROPERTY_FULFILLED = `${PREFIX}DELETE_TYPEPROPERTY_FULFILLED`;
export const DELETE_TYPEPROPERTY_REJECTED = `${PREFIX}DELETE_TYPEPROPERTY_REJECTED`;
export const BATCH_UPDATE_TYPEPROPERTY_REQUEST = `${PREFIX}BATCH_UPDATE_TYPEPROPERTY_REQUEST`;
export const BATCH_UPDATE_TYPEPROPERTY_FULFILLED = `${PREFIX}BATCH_UPDATE_TYPEPROPERTY_FULFILLED`;
export const BATCH_UPDATE_TYPEPROPERTY_REJECTED = `${PREFIX}BATCH_UPDATE_TYPEPROPERTY_REJECTED`;

/**
 * Sync
 */
export const FETCH_SYNC_REQUEST = `${PREFIX}FETCH_SYNC_REQUEST`;
export const FETCH_SYNC_FULFILLED = `${PREFIX}FETCH_SYNC_FULFILLED`;
export const FETCH_SYNC_REJECTED = `${PREFIX}FETCH_SYNC_REJECTED`;

/**
 * Services
 */
export const FETCH_SERVICESPECS_REQUEST = `${PREFIX}FETCH_SERVICESPECS_REQUEST`;
export const FETCH_SERVICESPECS_FULFILLED = `${PREFIX}FETCH_SERVICESPECS_FULFILLED`;
export const FETCH_SERVICESPECS_REJECTED = `${PREFIX}FETCH_SERVICESPECS_REJECTED`;
export const UNLOAD_SERVICESPECS = `${PREFIX}UNLOAD_SERVICESPECS`;
export const CREATE_SERVICESPEC_REQUEST = `${PREFIX}CREATE_SERVICESPEC_REQUEST`;
export const CREATE_SERVICESPEC_FULFILLED = `${PREFIX}CREATE_SERVICESPEC_FULFILLED`;
export const CREATE_SERVICESPEC_REJECTED = `${PREFIX}CREATE_SERVICESPEC_REJECTED`;
export const FETCH_SERVICESPECS_DROPDOWN_REQUEST = `${PREFIX}FETCH_SERVICESPECS_DROPDOWN_REQUEST`;
export const FETCH_SERVICESPECS_DROPDOWN_FULFILLED = `${PREFIX}FETCH_SERVICESPECS_DROPDOWN_FULFILLED`;
export const FETCH_SERVICESPECS_DROPDOWN_REJECTED = `${PREFIX}FETCH_SERVICESPECS_DROPDOWN_REJECTED`;

/**
 * Data Feeds
 */
export const FETCH_DATAFEEDS_REQUEST = `${PREFIX}FETCH_DATAFEEDS_REQUEST`;
export const FETCH_DATAFEEDS_FULFILLED = `${PREFIX}FETCH_DATAFEEDS_FULFILLED`;
export const FETCH_DATAFEEDS_REJECTED = `${PREFIX}FETCH_DATAFEEDS_REJECTED`;

export const DELETE_DATAFEEDS_REQUEST = `${PREFIX}DELETE_DATAFEEDS_REQUEST`;
export const DELETE_DATAFEEDS_FULFILLED = `${PREFIX}DELETE_DATAFEEDS_FULFILLED`;
export const DELETE_DATAFEEDS_REJECTED = `${PREFIX}DELETE_DATAFEEDS_REJECTED`;

export const FETCH_DATAFEED_REQUEST = `${PREFIX}FETCH_DATAFEED_REQUEST`;
export const FETCH_DATAFEED_FULFILLED = `${PREFIX}FETCH_DATAFEED_FULFILLED`;
export const FETCH_DATAFEED_REJECTED = `${PREFIX}FETCH_DATAFEED_REJECTED`;

export const CREATE_DATAFEED_REQUEST = `${PREFIX}CREATE_DATAFEED_REQUEST`;
export const CREATE_DATAFEED_FULFILLED = `${PREFIX}CREATE_DATAFEED_FULFILLED`;
export const CREATE_DATAFEED_REJECTED = `${PREFIX}CREATE_DATAFEED_REJECTED`;

export const UPDATE_DATAFEED_REQUEST = `${PREFIX}UPDATE_DATAFEED_REQUEST`;
export const UPDATE_DATAFEED_FULFILLED = `${PREFIX}UPDATE_DATAFEED_FULFILLED`;
export const UPDATE_DATAFEED_REJECTED = `${PREFIX}UPDATE_DATAFEED_REJECTED`;

export const DELETE_DATAFEED_REQUEST = `${PREFIX}DELETE_DATAFEED_REQUEST`;
export const DELETE_DATAFEED_FULFILLED = `${PREFIX}DELETE_DATAFEED_FULFILLED`;
export const DELETE_DATAFEED_REJECTED = `${PREFIX}DELETE_DATAFEED_REJECTED`;

export const UNLOAD_DATAFEEDS = `${PREFIX}UNLOAD_DATAFEEDS`;
export const UNLOAD_DATAFEED = `${PREFIX}UNLOAD_DATAFEED`;

/**
 * Stream Specs
 */
export const FETCH_STREAMSPECS_REQUEST = `${PREFIX}FETCH_STREAMSPECS_REQUEST`;
export const FETCH_STREAMSPECS_FULFILLED = `${PREFIX}FETCH_STREAMSPECS_FULFILLED`;
export const FETCH_STREAMSPECS_REJECTED = `${PREFIX}FETCH_STREAMSPECS_REJECTED`;

export const DELETE_STREAMSPECS_REQUEST = `${PREFIX}DELETE_STREAMSPECS_REQUEST`;
export const DELETE_STREAMSPECS_FULFILLED = `${PREFIX}DELETE_STREAMSPECS_FULFILLED`;
export const DELETE_STREAMSPECS_REJECTED = `${PREFIX}DELETE_STREAMSPECS_REJECTED`;

export const FETCH_STREAMSPEC_REQUEST = `${PREFIX}FETCH_STREAMSPEC_REQUEST`;
export const FETCH_STREAMSPEC_FULFILLED = `${PREFIX}FETCH_STREAMSPEC_FULFILLED`;
export const FETCH_STREAMSPEC_REJECTED = `${PREFIX}FETCH_STREAMSPEC_REJECTED`;

export const CREATE_STREAMSPEC_REQUEST = `${PREFIX}CREATE_STREAMSPEC_REQUEST`;
export const CREATE_STREAMSPEC_FULFILLED = `${PREFIX}CREATE_STREAMSPEC_FULFILLED`;
export const CREATE_STREAMSPEC_REJECTED = `${PREFIX}CREATE_STREAMSPEC_REJECTED`;

export const UPDATE_STREAMSPEC_REQUEST = `${PREFIX}UPDATE_STREAMSPEC_REQUEST`;
export const UPDATE_STREAMSPEC_FULFILLED = `${PREFIX}UPDATE_STREAMSPEC_FULFILLED`;
export const UPDATE_STREAMSPEC_REJECTED = `${PREFIX}UPDATE_STREAMSPEC_REJECTED`;

export const DELETE_STREAMSPEC_REQUEST = `${PREFIX}DELETE_STREAMSPEC_REQUEST`;
export const DELETE_STREAMSPEC_FULFILLED = `${PREFIX}DELETE_STREAMSPEC_FULFILLED`;
export const DELETE_STREAMSPEC_REJECTED = `${PREFIX}DELETE_STREAMSPEC_REJECTED`;

export const UNLOAD_STREASPECS = `${PREFIX}UNLOAD_STREASPECS`;
export const UNLOAD_STREAMSPEC = `${PREFIX}UNLOAD_STREAMSPEC`;
