export const FETCH_LICENSE_PENDING = 'license/FETCH_LICENSE_PENDING';
export const FETCH_LICENSE_FULFILLED = 'license/FETCH_LICENSE_FULFILLED';
export const FETCH_LICENSE_REJECTED = 'license/FETCH_LICENSE_REJECTED';

export const UPDATE_LICENSE_PENDING = 'license/UPDATE_LICENSE_PENDING';
export const UPDATE_LICENSE_FULFILLED = 'license/UPDATE_LICENSE_FULFILLED';
export const UPDATE_LICENSE_REJECTED = 'license/UPDATE_LICENSE_REJECTED';

export const LICENSE_UNLOADED = 'license/LICENSE_UNLOADED';

export const LICENSE_EXPIRING = 'license/LICENSE_EXPIRING';
export const LICENSE_EXPIRED = 'license/LICENSE_EXPIRED';
