import { PREFIX } from '../../constants';

export const FETCH_USERPROFILE_REQUEST = `${PREFIX}FETCH_USERPROFILE_REQUEST`;
export const FETCH_USERPROFILE_FULFILLED = `${PREFIX}FETCH_USERPROFILE_FULFILLED`;
export const FETCH_USERPROFILE_REJECTED = `${PREFIX}FETCH_USERPROFILE_REJECTED`;

export const CREATE_USERPROFILE_REQUEST = `${PREFIX}CREATE_USERPROFILE_REQUEST`;
export const CREATE_USERPROFILE_FULFILLED = `${PREFIX}CREATE_USERPROFILE_FULFILLED`;
export const CREATE_USERPROFILE_REJECTED = `${PREFIX}CREATE_USERPROFILE_REJECTED`;

export const UPDATE_USERPROFILE_REQUEST = `${PREFIX}UPDATE_USERPROFILE_REQUEST`;
export const UPDATE_USERPROFILE_FULFILLED = `${PREFIX}UPDATE_USERPROFILE_FULFILLED`;
export const UPDATE_USERPROFILE_REJECTED = `${PREFIX}UPDATE_USERPROFILE_REJECTED`;

export const CREATE_FAVORITE_REQUEST = `${PREFIX}CREATE_FAVORITE_REQUEST`;
export const CREATE_FAVORITE_FULFILLED = `${PREFIX}CREATE_FAVORITE_FULFILLED`;
export const CREATE_FAVORITE_REJECTED = `${PREFIX}CREATE_FAVORITE_REJECTED`;

export const UPDATE_FAVORITE_REQUEST = `${PREFIX}UPDATE_FAVORITE_REQUEST`;
export const UPDATE_FAVORITE_FULFILLED = `${PREFIX}UPDATE_FAVORITE_FULFILLED`;
export const UPDATE_FAVORITE_REJECTED = `${PREFIX}UPDATE_FAVORITE_REJECTED`;

export const DELETE_FAVORITE_REQUEST = `${PREFIX}DELETE_FAVORITE_REQUEST`;
export const DELETE_FAVORITE_FULFILLED = `${PREFIX}DELETE_FAVORITE_FULFILLED`;
export const DELETE_FAVORITE_REJECTED = `${PREFIX}DELETE_FAVORITE_REJECTED`;

export default {
  FETCH_USERPROFILE_REQUEST,
  FETCH_USERPROFILE_FULFILLED,
  FETCH_USERPROFILE_REJECTED,
  CREATE_USERPROFILE_REQUEST,
  CREATE_USERPROFILE_FULFILLED,
  CREATE_USERPROFILE_REJECTED,
  UPDATE_USERPROFILE_REQUEST,
  UPDATE_USERPROFILE_FULFILLED,
  UPDATE_USERPROFILE_REJECTED,
  CREATE_FAVORITE_REQUEST,
  CREATE_FAVORITE_FULFILLED,
  CREATE_FAVORITE_REJECTED,
  UPDATE_FAVORITE_REQUEST,
  UPDATE_FAVORITE_FULFILLED,
  UPDATE_FAVORITE_REJECTED,
  DELETE_FAVORITE_REQUEST,
  DELETE_FAVORITE_FULFILLED,
  DELETE_FAVORITE_REJECTED,
};
