export const FETCH_SELF_PENDING = 'app/FETCH_SELF_PENDING';
export const FETCH_SELF_FULFILLED = 'app/FETCH_SELF_FULFILLED';
export const FETCH_SELF_REJECTED = 'app/FETCH_SELF_REJECTED';

export const FETCH_ORG_CONTEXT_PENDING = 'app/FETCH_ORG_PENDING';
export const FETCH_ORG_CONTEXT_FULFILLED = 'app/FETCH_ORG_FULFILLED';
export const FETCH_ORG_CONTEXT_REJECTED = 'app/FETCH_ORG_REJECTED';

export const CURRENT_ORG_CONTEXT = 'app/CURRENT_ORG_CONTEXT';

export const LOG_OUT = 'app/LOG_OUT';
