export const FETCH_SELF_PENDING = 'app/FETCH_SELF_PENDING';
export const FETCH_SELF_FULFILLED = 'app/FETCH_SELF_FULFILLED';
export const FETCH_SELF_REJECTED = 'app/FETCH_SELF_REJECTED';

export const FETCH_ORG_CONTEXT_PENDING = 'app/FETCH_ORG_PENDING';
export const FETCH_ORG_CONTEXT_FULFILLED = 'app/FETCH_ORG_FULFILLED';
export const FETCH_ORG_CONTEXT_REJECTED = 'app/FETCH_ORG_REJECTED';

export const FETCH_WORKSPACE_CONTEXT_PENDING = 'app/FETCH_WORKSPACE_PENDING';
export const FETCH_WORKSPACE_CONTEXT_FULFILLED = 'app/FETCH_WORKSPACE_FULFILLED';
export const FETCH_WORKSPACE_CONTEXT_REJECTED = 'app/FETCH_WORKSPACE_REJECTED';

export const FETCH_ENVIRONMENT_CONTEXT_PENDING = 'app/FETCH_ENVIRONMENT_PENDING';
export const FETCH_ENVIRONMENT_CONTEXT_FULFILLED = 'app/FETCH_ENVIRONMENT_FULFILLED';
export const FETCH_ENVIRONMENT_CONTEXT_REJECTED = 'app/FETCH_ENVIRONMENT_REJECTED';

export const CURRENT_ORG_CONTEXT = 'app/CURRENT_ORG_CONTEXT';
export const CURRENT_WORKSPACE_CONTEXT = 'app/CURRENT_WORKSPACE_CONTEXT';
export const CURRENT_ENVIRONMENT_CONTEXT = 'app/CURRENT_ENVIRONMENT_CONTEXT';

export const UNLOAD_CURRENT_WORKSPACE_CONTEXT = 'app/UNLOAD_CURRENT_WORKSPACE_CONTEXT';
export const UNLOAD_CURRENT_ENVIRONMENT_CONTEXT = 'app/UNLOAD_CURRENT_ENVIRONMENT_CONTEXT';

export const APP_HTTP_REQUEST = 'app/APP_HTTP_REQUEST';

