export const UNLOAD_CURRENT_WORKSPACE_CONTEXT = 'app/UNLOAD_CURRENT_WORKSPACE_CONTEXT';
export const UNLOAD_CURRENT_ENVIRONMENT_CONTEXT = 'app/UNLOAD_CURRENT_ENVIRONMENT_CONTEXT';

export const APP_HTTP_REQUEST = 'app/APP_HTTP_REQUEST';
