export const SELECTED_PROVIDERS = 'providers/SELECTED_PROVIDERS';

export const FETCH_KONG_SCHEMA_PENDING = 'providers/FETCH_KONG_SCHEMA_PENDING';
export const FETCH_KONG_SCHEMA_FULFILLED = 'providers/FETCH_KONG_SCHEMA_FULFILLED';
export const FETCH_KONG_SCHEMA_REJECTED = 'providers/FETCH_KONG_SCHEMA_REJECTED';
export const FETCH_GATEWAYMANAGER_SCHEMA_PENDING = 'providers/FETCH_GATEWAYMANAGER_SCHEMA_PENDING';
export const FETCH_GATEWAYMANAGER_SCHEMA_FULFILLED = 'providers/FETCH_GATEWAYMANAGER_SCHEMA_FULFILLED';
export const FETCH_GATEWAYMANAGER_SCHEMA_REJECTED = 'providers/FETCH_GATEWAYMANAGER_SCHEMA_REJECTED';
export const FETCH_CAAS_SCHEMA_PENDING = 'providers/FETCH_CAAS_SCHEMA_PENDING';
export const FETCH_CAAS_SCHEMA_FULFILLED = 'providers/FETCH_CAAS_SCHEMA_FULFILLED';
export const FETCH_CAAS_SCHEMA_REJECTED = 'providers/FETCH_CAAS_SCHEMA_REJECTED';

export const FETCH_CONTAINER_PENDING = 'providers/FETCH_CONTAINER_PENDING';
export const FETCH_CONTAINER_FULFILLED = 'providers/FETCH_CONTAINER_FULFILLED';
export const FETCH_CONTAINER_REJECTED = 'providers/FETCH_CONTAINER_REJECTED';
