export const FETCH_PROVIDERS_PENDING = 'providers/FETCH_PROVIDERS_PENDING';
export const FETCH_PROVIDERS_FULFILLED = 'providers/FETCH_PROVIDERS_FULFILLED';
export const FETCH_PROVIDERS_REJECTED = 'providers/FETCH_PROVIDERS_REJECTED';

export const FETCH_PROVIDER_PENDING = 'providers/FETCH_PROVIDER_PENDING';
export const FETCH_PROVIDER_FULFILLED = 'providers/FETCH_PROVIDER_FULFILLED';
export const FETCH_PROVIDER_REJECTED = 'providers/FETCH_PROVIDER_REJECTED';

export const CREATE_PROVIDER_PENDING = 'providers/CREATE_PROVIDER_PENDING';
export const CREATE_PROVIDER_FULFILLED = 'providers/CREATE_PROVIDER_FULFILLED';
export const CREATE_PROVIDER_REJECTED = 'providers/CREATE_PROVIDER_REJECTED';

export const UPDATE_PROVIDER_PENDING = 'providers/UPDATE_PROVIDER_PENDING';
export const UPDATE_PROVIDER_FULFILLED = 'providers/UPDATE_PROVIDER_FULFILLED';
export const UPDATE_PROVIDER_REJECTED = 'providers/UPDATE_PROVIDER_REJECTED';

export const DELETE_PROVIDER_PENDING = 'providers/DELETE_PROVIDER_PENDING';
export const DELETE_PROVIDER_FULFILLED = 'providers/DELETE_PROVIDER_FULFILLED';
export const DELETE_PROVIDER_REJECTED = 'providers/DELETE_PROVIDER_REJECTED';

export const SELECTED_PROVIDERS = 'providers/SELECTED_PROVIDERS';

export const PROVIDER_UNLOADED = 'providers/PROVIDER_UNLOADED';
export const PROVIDERS_UNLOADED = 'providers/PROVIDERS_UNLOADED';
