export const PREFIX = 'metaResource/';

// Select form states
export const SELECTED_PROVIDERTYPE_REQUEST = `${PREFIX}SELECTED_PROVIDERTYPE_REQUEST`;
export const SELECTED_PROVIDERTYPE_FULFILLED = `${PREFIX}SELECTED_PROVIDERTYPE_FULFILLED`;
export const SELECTED_PROVIDERTYPE_REJECTED = `${PREFIX}SELECTED_PROVIDERTYPE_REJECTED`;
export const UNLOAD_SELECTED_PROVIDERTYPE = `${PREFIX}UNLOAD_SELECTED_PROVIDERTYPE`;

// For initializing the provider create ui state
export const INIT_PROVIDERCREATE_REQUEST = `${PREFIX}INIT_PROVIDERCREATE_REQUEST`;
export const INIT_PROVIDERCREATE_FULFILLED = `${PREFIX}INIT_PROVIDERCREATE_FULFILLED`;
export const INIT_PROVIDERCREATE_REJECTED = `${PREFIX}INIT_PROVIDERCREATE_REJECTED`;
export const INIT_PROVIDERCREATE_CANCELLED = `${PREFIX}INIT_PROVIDERCREATE_CANCELLED`;

// For initializing the provider edit ui state
export const INIT_PROVIDEREDIT_REQUEST = `${PREFIX}INIT_PROVIDEREDIT_REQUEST`;
export const INIT_PROVIDEREDIT_FULFILLED = `${PREFIX}INIT_PROVIDEREDIT_FULFILLED`;
export const INIT_PROVIDEREDIT_REJECTED = `${PREFIX}INIT_PROVIDEREDIT_REJECTED`;
export const INIT_PROVIDEREDIT_CANCELLED = `${PREFIX}INIT_PROVIDEREDIT_CANCELLED`;

/**
 * Providers
 */
export const REDEPLOY_PROVIDER_REQUEST = `${PREFIX}REDEPLOY_PROVIDER_REQUEST`;
export const REDEPLOY_PROVIDER_FULFILLED = `${PREFIX}REDEPLOY_PROVIDER_FULFILLED`;
export const REDEPLOY_PROVIDER_REJECTED = `${PREFIX}REDEPLOY_PROVIDER_REJECTED`;

export const FETCH_PROVIDERS_REQUEST = `${PREFIX}FETCH_PROVIDERS_REQUEST`;
export const FETCH_PROVIDERS_FULFILLED = `${PREFIX}FETCH_PROVIDERS_FULFILLED`;
export const FETCH_PROVIDERS_REJECTED = `${PREFIX}FETCH_PROVIDERS_REJECTED`;
export const FETCH_PROVIDERS_CANCELLED = `${PREFIX}FETCH_PROVIDERS_CANCELLED`;

export const FETCH_PROVIDER_REQUEST = `${PREFIX}FETCH_PROVIDER_REQUEST`;
export const FETCH_PROVIDER_FULFILLED = `${PREFIX}FETCH_PROVIDER_FULFILLED`;
export const FETCH_PROVIDER_REJECTED = `${PREFIX}FETCH_PROVIDER_REJECTED`;
export const FETCH_PROVIDER_CANCELLED = `${PREFIX}FETCH_PROVIDER_CANCELLED`;

export const CREATE_PROVIDER_REQUEST = `${PREFIX}CREATE_PROVIDER_REQUEST`;
export const CREATE_PROVIDER_FULFILLED = `${PREFIX}CREATE_PROVIDER_FULFILLED`;
export const CREATE_PROVIDER_REJECTED = `${PREFIX}CREATE_PROVIDER_REJECTED`;

export const UPDATE_PROVIDER_REQUEST = `${PREFIX}UPDATE_PROVIDER_REQUEST`;
export const UPDATE_PROVIDER_FULFILLED = `${PREFIX}UPDATE_PROVIDER_FULFILLED`;
export const UPDATE_PROVIDER_REJECTED = `${PREFIX}UPDATE_PROVIDER_REJECTED`;

export const DELETE_PROVIDER_REQUEST = `${PREFIX}DELETE_PROVIDER_REQUEST`;
export const DELETE_PROVIDER_FULFILLED = `${PREFIX}DELETE_PROVIDER_FULFILLED`;
export const DELETE_PROVIDER_REJECTED = `${PREFIX}DELETE_PROVIDER_REJECTED`;

export const FETCH_PROVIDERCONTAINER_REQUEST = `${PREFIX}FETCH_PROVIDERCONTAINER_REQUEST`;
export const FETCH_PROVIDERCONTAINER_FULFILLED = `${PREFIX}FETCH_PROVIDERCONTAINER_FULFILLED`;
export const FETCH_PROVIDERCONTAINER_REJECTED = `${PREFIX}FETCH_PROVIDERCONTAINER_REJECTED`;

export const UNLOAD_PROVIDER = `${PREFIX}UNLOAD_PROVIDER`;
export const UNLOAD_PROVIDERS = `${PREFIX}UNLOAD_PROVIDERS`;
