export const PREFIX = 'metaResource/';

/**
 * Providers
 */
export const REDEPLOY_PROVIDER_REQUEST = `${PREFIX}REDEPLOY_PROVIDER_REQUEST`;
export const REDEPLOY_PROVIDER_FULFILLED = `${PREFIX}REDEPLOY_PROVIDER_FULFILLED`;
export const REDEPLOY_PROVIDER_REJECTED = `${PREFIX}REDEPLOY_PROVIDER_REJECTED`;
