export const FETCH_ORGS_PENDING = 'orgs/FETCH_ORGS_PENDING';
export const FETCH_ORGS_FULFILLED = 'orgs/FETCH_ORGS_FULFILLED';
export const FETCH_ORGS_REJECTED = 'orgs/FETCH_ORGS_REJECTED';

export const FETCH_ORG_PENDING = 'orgs/FETCH_ORG_PENDING';
export const FETCH_ORG_FULFILLED = 'orgs/FETCH_ORG_FULFILLED';
export const FETCH_ORG_REJECTED = 'orgs/FETCH_ORG_REJECTED';

export const FETCH_ORGSET_PENDING = 'orgs/FETCH_ORGSET_PENDING';
export const FETCH_ORGSET_FULFILLED = 'orgs/FETCH_ORGSET_FULFILLED';
export const FETCH_ORGSET_REJECTED = 'orgs/FETCH_ORGSET_REJECTED';

export const CREATE_ORG_PENDING = 'orgs/CREATE_ORG_PENDING';
export const CREATE_ORG_FULFILLED = 'orgs/CREATE_ORG_FULFILLED';
export const CREATE_ORG_REJECTED = 'orgs/CREATE_ORG_REJECTED';

export const UPDATE_ORG_PENDING = 'orgs/UPDATE_ORG_PENDING';
export const UPDATE_ORG_FULFILLED = 'orgs/UPDATE_ORG_FULFILLED';
export const UPDATE_ORG_REJECTED = 'orgs/UPDATE_ORG_REJECTED';

export const DELETE_ORG_PENDING = 'orgs/DELETE_ORG_PENDING';
export const DELETE_ORG_FULFILLED = 'orgs/DELETE_ORG_FULFILLED';
export const DELETE_ORG_REJECTED = 'orgs/DELETE_ORG_REJECTED';
