export const FETCH_APIS_PENDING = 'apis/FETCH_APIS_PENDING';
export const FETCH_APIS_FULFILLED = 'apis/FETCH_APIS_FULFILLED';
export const FETCH_APIS_REJECTED = 'apis/FETCH_APIS_REJECTED';

export const FETCH_API_PENDING = 'apis/FETCH_API_PENDING';
export const FETCH_API_FULFILLED = 'apis/FETCH_API_FULFILLED';
export const FETCH_API_REJECTED = 'apis/FETCH_API_REJECTED';

export const CREATE_API_PENDING = 'apis/CREATE_API_PENDING';
export const CREATE_API_FULFILLED = 'apis/CREATE_API_FULFILLED';
export const CREATE_API_REJECTED = 'apis/CREATE_API_REJECTED';

export const UPDATE_API_PENDING = 'apis/UPDATE_API_PENDING';
export const UPDATE_API_FULFILLED = 'apis/UPDATE_API_FULFILLED';
export const UPDATE_API_REJECTED = 'apis/UPDATE_API_REJECTED';

export const DELETE_API_PENDING = 'apis/DELETE_API_PENDING';
export const DELETE_API_FULFILLED = 'apis/DELETE_API_FULFILLED';
export const DELETE_API_REJECTED = 'apis/DELETE_API_REJECTED';

export const FETCH_PROVIDERS_PENDING = 'apis/FETCH_PROVIDERS_PENDING';
export const FETCH_PROVIDERS_FULFILLED = 'apis/FETCH_PROVIDERS_FULFILLED';
export const FETCH_PROVIDERS_REJECTED = 'apis/FETCH_PROVIDERS_REJECTED';

export const SELECTED_APIS = 'apis/SELECTED_APIS';

export const API_UNLOADED = 'apis/API_UNLOADED';
export const APIS_UNLOADED = 'apis/APIS_UNLOADED';

