export const PREFIX = 'metaResource/';

export const FETCH_UPGRADEAVAILABLE_REQUEST = `${PREFIX}FETCH_UPGRADEAVAILABLE_REQUEST`;
export const FETCH_UPGRADEAVAILABLE_FULFILLED = `${PREFIX}FETCH_UPGRADEAVAILABLE_FULFILLED`;
export const FETCH_UPGRADEAVAILABLE_REJECTED = `${PREFIX}FETCH_UPGRADEAVAILABLE_REJECTED`;

export const CLOSE_UPGRADEAVAILBALE = 'upgrader/FETCH_UPGRADEAVAILABLE_REJECTED';
