export const RESET_GROUP = 'groups/RESET_GROUP';

export const FILTER_AVAILABLE_USERS_TEXT = 'groups/FILTER_AVAILABLE_USERS_TEXT';
export const FILTER_MEMBER_USERS_TEXT = 'groups/FILTER_MEMBER_USERS_TEXT';
