export const FETCH_GROUPS_PENDING = 'groups/FETCH_GROUPS_PENDING';
export const FETCH_GROUPS_FULFILLED = 'groups/FETCH_GROUPS_FULFILLED';
export const FETCH_GROUPS_REJECTED = 'v/FETCH_GROUPS_REJECTED';
