export const FETCH_GROUPS_PENDING = 'groups/FETCH_GROUPS_PENDING';
export const FETCH_GROUPS_FULFILLED = 'groups/FETCH_GROUPS_FULFILLED';
export const FETCH_GROUPS_REJECTED = 'groups/FETCH_GROUPS_REJECTED';

export const FETCH_GROUP_PENDING = 'groups/FETCH_GROUP_PENDING';
export const FETCH_GROUP_FULFILLED = 'groups/FETCH_GROUP_FULFILLED';
export const FETCH_GROUP_REJECTED = 'groups/FETCH_GROUP_REJECTED';

export const CREATE_GROUP_PENDING = 'groups/CREATE_GROUP_PENDING';
export const CREATE_GROUP_FULFILLED = 'groups/CREATE_GROUP_FULFILLED';
export const CREATE_GROUP_REJECTED = 'groups/CREATE_GROUP_REJECTED';

export const UPDATE_GROUP_PENDING = 'groups/UPDATE_GROUP_PENDING';
export const UPDATE_GROUP_FULFILLED = 'groups/UPDATE_GROUP_FULFILLED';
export const UPDATE_GROUP_REJECTED = 'groups/UPDATE_GROUP_REJECTED';

export const DELETE_GROUP_PENDING = 'groups/DELETE_GROUP_PENDING';
export const DELETE_GROUP_FULFILLED = 'groups/DELETE_GROUP_FULFILLED';
export const DELETE_GROUP_REJECTED = 'groups/DELETE_GROUP_REJECTED';

export const FETCH_USERS_PENDING = 'groups/FETCH_USERS_PENDING';
export const FETCH_USERS_FULFILLED = 'groups/FETCH_USERS_FULFILLED';
export const FETCH_USERS_REJECTED = 'groups/FETCH_USERS_REJECTED';

export const SELECTED_GROUPS = 'groups/SELECTED_GROUPS';
export const SELECTED_GROUPS_CLEAR = 'groups/SELECTED_GROUPS_CLEAR';

export const ADD_GROUP_MEMBER_PENDING = 'groups/ADD_GROUP_MEMBER_PENDING';
export const ADD_GROUP_MEMBER_FULFILLED = 'groups/ADD_GROUP_MEMBER';
export const ADD_GROUP_MEMBER_REJECTED = 'groups/ADD_GROUP_MEMBER_REJECTED';
export const REMOVE_GROUP_MEMBER_PENDING = 'groups/REMOVE_GROUP_MEMBER_PENDING';
export const REMOVE_GROUP_MEMBER_FULFILLED = 'groups/REMOVE_GROUP_MEMBER_FULFILLED';
export const REMOVE_GROUP_MEMBER_REJECTED = 'groups/REMOVE_GROUP_MEMBER_REJECTED';

export const RESET_GROUP = 'groups/RESET_GROUP';
export const GROUP_UNLOADED = 'groups/GROUP_UNLOADED';
export const GROUPS_UNLOADED = 'groups/GROUPS_UNLOADED';

export const FILTER_AVAILABLE_USERS_TEXT = 'groups/FILTER_AVAILABLE_USERS_TEXT';
export const FILTER_MEMBER_USERS_TEXT = 'groups/FILTER_MEMBER_USERS_TEXT';
