export const PREFIX = 'metaResource/';

/**
 * Groups
 */
export const ADD_GROUPMEMBER_REQUEST = `${PREFIX}ADD_GROUPMEMBER_REQUEST`;
export const ADD_GROUPMEMBER_FULFILLED = `${PREFIX}ADD_GROUPMEMBER_FULFILLED`;
export const ADD_GROUPMEMBER_REJECTED = `${PREFIX}ADD_GROUPMEMBER_REJECTED`;
export const REMOVE_GROUPMEMBER_REQUEST = `${PREFIX}REMOVE_GROUPMEMBER_REQUEST`;
export const REMOVE_GROUPMEMBER_FULFILLED = `${PREFIX}REMOVE_GROUPMEMBER_FULFILLED`;
export const REMOVE_GROUPMEMBER_REJECTED = `${PREFIX}REMOVE_GROUPMEMBER_REJECTED`;
