/**
 * Actions for containment state management/switching. Typically, these are called when an org, workspace or
 * environment is navigated to.
 */
export const SET_CURRENT_ORG_CONTEXT_REQUEST = 'contextManager/SET_CURRENT_ORG_CONTEXT_REQUEST';
export const SET_CURRENT_ORG_CONTEXT_PENDING = 'contextManager/SET_CURRENT_ORG_CONTEXT_PENDING';
export const SET_CURRENT_ORG_CONTEXT_REJECTED = 'contextManager/SET_CURRENT_ORG_CONTEXT_REJECTED';

export const SET_CURRENT_WORKSPACE_CONTEXT_REQUEST = 'contextManager/SET_CURRENT_WORKSPACE_CONTEXT_REQUEST';
export const SET_CURRENT_WORKSPACE_CONTEXT_PENDING = 'contextManager/SET_CURRENT_WORKSPACE_CONTEXT_PENDING';
export const SET_CURRENT_WORKSPACE_CONTEXT_REJECTED = 'contextManager/SET_CURRENT_WORKSPACE_CONTEXT_REJECTED';

export const SET_CURRENT_ENVIRONMENT_CONTEXT_REQUEST = 'contextManager/SET_CURRENT_ENVIRONMENT_CONTEXT_REQUEST';
export const SET_CURRENT_ENVIRONMENT_CONTEXT_PENDING = 'contextManager/SET_CURRENT_ENVIRONMENT_CONTEXT_PENDING';
export const SET_CURRENT_ENVIRONMENT_CONTEXT_REJECTED = 'contextManager/SET_CURRENT_ENVIRONMENT_CONTEXT_REJECTED';

export const UPDATE_CURRENT_ORG_CONTEXT = 'contextManager/UPDATE_CURRENT_ORG_CONTEXT';
export const UPDATE_CURRENT_WORKSPACE_CONTEXT = 'contextManager/UPDATE_CURRENT_WORKSPACE_CONTEXT';
export const UPDATE_CURRENT_ENVIRONMENT_CONTEXT = 'contextManager/UPDATE_CURRENT_ENVIRONMENT_CONTEXT';

export const UNLOAD_CURRENT_WORKSPACE_CONTEXT = 'contextManager/UNLOAD_CURRENT_WORKSPACE_CONTEXT';
export const UNLOAD_CURRENT_ENVIRONMENT_CONTEXT = 'contextManager/UNLOAD_CURRENT_ENVIRONMENT_CONTEXT';
