import { PREFIX } from '../../constants';

export const SELECT_RUNTIME = 'lambdas/SELECT_RUNTIME';

// For initializing the lambda create ui state
export const INIT_LAMBDACREATE_REQUEST = `${PREFIX}INIT_LAMBDACREATE_REQUEST`;
export const INIT_LAMBDACREATE_FULFILLED = `${PREFIX}INIT_LAMBDACREATE_FULFILLED`;
export const INIT_LAMBDACREATE_REJECTED = `${PREFIX}INIT_LAMBDACREATE_REJECTED`;
export const INIT_LAMBDACREATE_CANCELLED = `${PREFIX}INIT_LAMBDACREATE_CANCELLED`;

// For initializing the lambda edit ui state
export const INIT_LAMBDAEDIT_REQUEST = `${PREFIX}INIT_LAMBDAEDIT_REQUEST`;
export const INIT_LAMBDAEDIT_FULFILLED = `${PREFIX}INIT_LAMBDAEDIT_FULFILLED`;
export const INIT_LAMBDAEDIT_REJECTED = `${PREFIX}INIT_LAMBDAEDIT_REJECTED`;
export const INIT_LAMBDAEDIT_CANCELLED = `${PREFIX}INIT_LAMBDAEDIT_CANCELLED`;

// pertaining to listing view
export const FETCH_LAMBDAS_REQUEST = `${PREFIX}FETCH_LAMBDAS_REQUEST`;
export const FETCH_LAMBDAS_FULFILLED = `${PREFIX}FETCH_LAMBDAS_FULFILLED`;
export const FETCH_LAMBDAS_REJECTED = `${PREFIX}FETCH_LAMBDAS_REJECTED`;
export const FETCH_LAMBDAS_CANCELLED = `${PREFIX}FETCH_LAMBDAS_CANCELLED`;
export const CREATE_LAMBDAS_REQUEST = `${PREFIX}CREATE_LAMBDAS_REQUEST`;
export const CREATE_LAMBDAS_FULFILLED = `${PREFIX}CREATE_LAMBDAS_FULFILLED`;
export const CREATE_LAMBDAS_REJECTED = `${PREFIX}CREATE_LAMBDAS_REJECTED`;
export const DELETE_LAMBDAS_REQUEST = `${PREFIX}DELETE_LAMBDAS_REQUEST`;

// cleanup
export const UNLOAD_LAMBDAS = `${PREFIX}UNLOAD_LAMBDAS`;
export const UNLOAD_LAMBDA = `${PREFIX}UNLOAD_LAMBDA`;

// General API calls
export const CREATE_LAMBDA_REQUEST = `${PREFIX}CREATE_LAMBDA_REQUEST`;
export const CREATE_LAMBDA_FULFILLED = `${PREFIX}CREATE_LAMBDA_FULFILLED`;
export const CREATE_LAMBDA_REJECTED = `${PREFIX}CREATE_LAMBDA_REJECTED`;

export const UPDATE_LAMBDA_REQUEST = `${PREFIX}UPDATE_LAMBDA_REQUEST`;
export const UPDATE_LAMBDA_FULFILLED = `${PREFIX}UPDATE_LAMBDA_FULFILLED`;
export const UPDATE_LAMBDA_REJECTED = `${PREFIX}UPDATE_LAMBDA_REJECTED`;

export const DELETE_LAMBDA_REQUEST = `${PREFIX}DELETE_LAMBDA_REQUEST`;
export const DELETE_LAMBDA_FULFILLED = `${PREFIX}DELETE_LAMBDA_FULFILLED`;
export const DELETE_LAMBDA_REJECTED = `${PREFIX}DELETE_LAMBDA_REJECTED`;
