export const FETCH_PROVIDERS_REQUEST = 'lambdas/FETCH_PROVIDERS_REQUESTs';
export const FETCH_PROVIDERS_FULFILLED = 'lambdas/FETCH_PROVIDERS_FULFILLED';
export const FETCH_PROVIDERS_REJECTED = 'lambdas/FETCH_PROVIDERS_REJECTED';

export const SELECTED_LAMBDAS = 'lambdas/SELECTED_LAMBDAS';

export const FETCH_ENV_REQUEST = 'lambdas/FETCH_ENV_REQUEST';
export const FETCH_ENV_FULFILLED = 'lambdas/FETCH_ENV_FULFILLED';
export const FETCH_ENV_REJECTED = 'lambdas/FETCH_ENV_REJECTED';

export const FETCH_EXECUTORS_REQUEST = 'lambdas/FETCH_EXECUTORS_REQUEST';
export const FETCH_EXECUTORS_FULFILLED = 'lambdas/FETCH_EXECUTORS_FULFILLED';
export const FETCH_EXECUTORS_REJECTED = 'lambdas/FETCH_EXECUTORS_REJECTED';

export const CHANGE_EDITOR_THEME = 'lambdas/CHANGE_EDITOR_THEME';
