export const FETCH_LAMBDAS_PENDING = 'lambdas/FETCH_LAMBDAS_PENDING';
export const FETCH_LAMBDAS_FULFILLED = 'lambdas/FETCH_LAMBDAS_FULFILLED';
export const FETCH_LAMBDAS_REJECTED = 'lambdas/FETCH_LAMBDAS_REJECTED';

export const FETCH_LAMBDA_PENDING = 'lambdas/FETCH_LAMBDA_PENDING';
export const FETCH_LAMBDA_FULFILLED = 'lambdas/FETCH_LAMBDA_FULFILLED';
export const FETCH_LAMBDA_REJECTED = 'lambdas/FETCH_LAMBDA_REJECTED';

export const CREATE_LAMBDA_PENDING = 'lambdas/CREATE_LAMBDA_PENDING';
export const CREATE_LAMBDA_FULFILLED = 'lambdas/CREATE_LAMBDA_FULFILLED';
export const CREATE_LAMBDA_REJECTED = 'lambdas/CREATE_LAMBDA_REJECTED';

export const UPDATE_LAMBDA_PENDING = 'lambdas/UPDATE_LAMBDA_PENDING';
export const UPDATE_LAMBDA_FULFILLED = 'lambdas/UPDATE_LAMBDA_FULFILLED';
export const UPDATE_LAMBDA_REJECTED = 'lambdas/UPDATE_LAMBDA_REJECTED';

export const DELETE_LAMBDA_PENDING = 'lambdas/DELETE_LAMBDA_PENDING';
export const DELETE_LAMBDA_FULFILLED = 'lambdas/DELETE_LAMBDA_FULFILLED';
export const DELETE_LAMBDA_REJECTED = 'lambdas/DELETE_LAMBDA_REJECTED';
