export const PREFIX = 'metaResource/';

export const SELECT_RUNTIME = 'lambdas/SELECT_RUNTIME';

/**
 * Lambdas
 */
export const FETCH_LAMBDAS_REQUEST = `${PREFIX}FETCH_LAMBDAS_REQUEST`;
export const FETCH_LAMBDAS_FULFILLED = `${PREFIX}FETCH_LAMBDAS_FULFILLED`;
export const FETCH_LAMBDAS_REJECTED = `${PREFIX}FETCH_LAMBDAS_REJECTED`;
export const FETCH_LAMBDAS_CANCELLED = `${PREFIX}FETCH_LAMBDAS_CANCELLED`;

export const FETCH_LAMBDA_REQUEST = `${PREFIX}FETCH_LAMBDA_REQUEST`;
export const FETCH_LAMBDA_FULFILLED = `${PREFIX}FETCH_LAMBDA_FULFILLED`;
export const FETCH_LAMBDA_REJECTED = `${PREFIX}FETCH_LAMBDA_REJECTED`;

export const CREATE_LAMBDA_REQUEST = `${PREFIX}CREATE_LAMBDA_REQUEST`;
export const CREATE_LAMBDA_FULFILLED = `${PREFIX}CREATE_LAMBDA_FULFILLED`;
export const CREATE_LAMBDA_REJECTED = `${PREFIX}CREATE_LAMBDA_REJECTED`;

export const UPDATE_LAMBDA_REQUEST = `${PREFIX}UPDATE_LAMBDA_REQUEST`;
export const UPDATE_LAMBDA_FULFILLED = `${PREFIX}UPDATE_LAMBDA_FULFILLED`;
export const UPDATE_LAMBDA_REJECTED = `${PREFIX}UPDATE_LAMBDA_REJECTED`;

export const DELETE_LAMBDAS_REQUEST = `${PREFIX}DELETE_LAMBDAS_REQUEST`;
export const DELETE_LAMBDA_REQUEST = `${PREFIX}DELETE_LAMBDA_REQUEST`;
export const DELETE_LAMBDA_FULFILLED = `${PREFIX}DELETE_LAMBDA_FULFILLED`;
export const DELETE_LAMBDA_REJECTED = `${PREFIX}DELETE_LAMBDA_REJECTED`;
