export const CREATE_WORKSPACE_PENDING = 'workspace/CREATE_WORKSPACE_PENDING';
export const CREATE_WORKSPACE_FULFILLED = 'workspace/CREATE_WORKSPACE_FULFILLED';
export const CREATE_WORKSPACE_REJECTED = 'workspace/CREATE_WORKSPACE_REJECTED';

export const UPDATE_WORKSPACE_PENDING = 'workspace/UPDATE_WORKSPACE_PENDING';
export const UPDATE_WORKSPACE_FULFILLED = 'workspace/UPDATE_WORKSPACE_FULFILLED';
export const UPDATE_WORKSPACE_REJECTED = 'workspace/UPDATE_WORKSPACE_REJECTED';

export const DELETE_WORKSPACE_PENDING = 'workspace/DELETE_WORKSPACE_PENDING';
export const DELETE_WORKSPACE_FULFILLED = 'workspace/DELETE_WORKSPACE_FULFILLED';
export const DELETE_WORKSPACE_REJECTED = 'workspace/DELETE_WORKSPACE_REJECTED';

export const WORKSPACES_NAVIGATION = 'workspace/WORKSPACES_NAVIGATION';

export const WORKSPACE_UNLOADED = 'workspace/WORKSPACE_UNLOADED';
export const WORKSPACES_UNLOADED = 'workspace/WORKSPACES_UNLOADED';
