export const AUTH_TOKEN_REQUEST = 'auth/AUTH_TOKEN_REQUEST';
export const AUTH_TOKEN_FULFILLED = 'auth/AUTH_TOKEN_FULFILLED';
export const AUTH_TOKEN_REJECTED = 'auth/AUTH_TOKEN_REJECTED';
export const LOGOUT_REQUEST = 'auth/LOGOUT_REQUEST';
export const LOGOUT_FULFILLED = 'auth/LOGOUT_FULFILLED';
export const LOGOUT_REJECTED = 'auth/LOGOUT_REJECTED';

export default {
  AUTH_TOKEN_REQUEST,
  AUTH_TOKEN_FULFILLED,
  AUTH_TOKEN_REJECTED,
  LOGOUT_REQUEST,
  LOGOUT_FULFILLED,
  LOGOUT_REJECTED,
};
