export const FETCH_INTEGRATIONS_PENDING = 'integrations/FETCH_INTEGRATIONS_PENDING';
export const FETCH_INTEGRATIONS_FULFILLED = 'integrations/FETCH_INTEGRATIONS_FULFILLED';
export const FETCH_INTEGRATIONS_REJECTED = 'integrations/FETCH_INTEGRATIONS_REJECTED';
