export const PREFIX = 'metaResource/';

/**
 * Env
 */
export const FETCH_ENV_REQUEST = `${PREFIX}FETCH_ENV_REQUEST`;
export const FETCH_ENV_FULFILLED = `${PREFIX}FETCH_ENV_FULFILLED`;
export const FETCH_ENV_REJECTED = `${PREFIX}FETCH_ENV_REJECTED`;

export const FETCH_ENVSCHEMA_REQUEST = `${PREFIX}FETCH_ENVSCHEMA_REQUEST`;
export const FETCH_ENVSCHEMA_FULFILLED = `${PREFIX}FETCH_ENVSCHEMA_FULFILLED`;
export const FETCH_ENVSCHEMA_REJECTED = `${PREFIX}FETCH_ENVSCHEMA_REJECTED`;

export const UNLOAD_ENVSCHEMA = `${PREFIX}UNLOAD_ENVSCHEMA`;
