export const FETCH_ENVIRONMENTS_PENDING = 'environment/FETCH_ENVIRONMENTS_PENDING';
export const FETCH_ENVIRONMENTS_FULFILLED = 'environment/FETCH_ENVIRONMENTS_FULFILLED';
export const FETCH_ENVIRONMENTS_REJECTED = 'environment/FETCH_ENVIRONMENTS_REJECTED';

export const FETCH_ENVIRONMENT_PENDING = 'environment/FETCH_ENVIRONMENT_PENDING';
export const FETCH_ENVIRONMENT_FULFILLED = 'environment/FETCH_ENVIRONMENT_FULFILLED';
export const FETCH_ENVIRONMENT_REJECTED = 'environment/FETCH_ENVIRONMENT_REJECTED';

export const CREATE_ENVIRONMENT_PENDING = 'environment/CREATE_ENVIRONMENT_PENDING';
export const CREATE_ENVIRONMENT_FULFILLED = 'environment/CREATE_ENVIRONMENT_FULFILLED';
export const CREATE_ENVIRONMENT_REJECTED = 'environment/CREATE_ENVIRONMENT_REJECTED';

export const UPDATE_ENVIRONMENT_PENDING = 'environment/UPDATE_ENVIRONMENT_PENDING';
export const UPDATE_ENVIRONMENT_FULFILLED = 'environment/UPDATE_ENVIRONMENT_FULFILLED';
export const UPDATE_ENVIRONMENT_REJECTED = 'environment/UPDATE_ENVIRONMENT_REJECTED';

export const DELETE_ENVIRONMENT_PENDING = 'environment/DELETE_ENVIRONMENT_PENDING';
export const DELETE_ENVIRONMENT_FULFILLED = 'environment/DELETE_ENVIRONMENT_FULFILLED';
export const DELETE_ENVIRONMENT_REJECTED = 'environment/DELETE_ENVIRONMENT_REJECTED';

export const ENVIRONMENTS_NAVIGATION = 'environments/ENVIRONMENTS_NAVIGATION';

export const ENVIRONMENT_UNLOADED = 'environment/ENVIRONMENT_UNLOADED';
export const ENVIRONMENTS_UNLOADED = 'environment/ENVIRONMENTS_UNLOADED';
