import { PREFIX } from '../../constants';

/**
 * Type Properties
 */
export const CREATE_TYPEPROPERTY_REQUEST = `${PREFIX}CREATE_TYPEPROPERTY_REQUEST`;
export const CREATE_TYPEPROPERTY_FULFILLED = `${PREFIX}CREATE_TYPEPROPERTY_FULFILLED`;
export const CREATE_TYPEPROPERTY_REJECTED = `${PREFIX}CREATE_TYPEPROPERTY_REJECTED`;
export const UPDATE_TYPEPROPERTY_REQUEST = `${PREFIX}UPDATE_TYPEPROPERTY_REQUEST`;
export const UPDATE_TYPEPROPERTY_FULFILLED = `${PREFIX}UPDATE_TYPEPROPERTY_FULFILLED`;
export const UPDATE_TYPEPROPERTY_REJECTED = `${PREFIX}UPDATE_TYPEPROPERTY_REJECTED`;
export const DELETE_TYPEPROPERTY_REQUEST = `${PREFIX}DELETE_TYPEPROPERTY_REQUEST`;
export const DELETE_TYPEPROPERTY_FULFILLED = `${PREFIX}DELETE_TYPEPROPERTY_FULFILLED`;
export const DELETE_TYPEPROPERTY_REJECTED = `${PREFIX}DELETE_TYPEPROPERTY_REJECTED`;
export const BATCH_UPDATE_TYPEPROPERTY_REQUEST = `${PREFIX}BATCH_UPDATE_TYPEPROPERTY_REQUEST`;
export const BATCH_UPDATE_TYPEPROPERTY_FULFILLED = `${PREFIX}BATCH_UPDATE_TYPEPROPERTY_FULFILLED`;
export const BATCH_UPDATE_TYPEPROPERTY_REJECTED = `${PREFIX}BATCH_UPDATE_TYPEPROPERTY_REJECTED`;
