export const REQUEST_TOKEN_PENDING = 'login/REQUEST_TOKEN_PENDING';
export const REQUEST_TOKEN_FULFILLED = 'login/REQUEST_TOKEN_FULFILLED';
export const REQUEST_TOKEN_REJECTED = 'login/REQUEST_TOKEN_REJECTED';

