export const REQUEST_TOKEN_PENDING = 'auth/REQUEST_TOKEN_PENDING';
export const REQUEST_TOKEN_FULFILLED = 'auth/REQUEST_TOKEN_FULFILLED';
export const REQUEST_TOKEN_REJECTED = 'auth/REQUEST_TOKEN_REJECTED';
export const LOG_OUT = 'auth/LOG_OUT';
