export const FETCH_CONTAINERS_PENDING = 'containers/FETCH_CONTAINERS_PENDING';
export const FETCH_CONTAINERS_FULFILLED = 'containers/FETCH_CONTAINERS_FULFILLED';
export const FETCH_CONTAINERS_REJECTED = 'containers/FETCH_CONTAINERS_REJECTED';
