export const FETCH_CONTAINERS_PENDING = 'containers/FETCH_CONTAINERS_PENDING';
export const FETCH_CONTAINERS_FULFILLED = 'containers/FETCH_CONTAINERS_FULFILLED';
export const FETCH_CONTAINERS_REJECTED = 'containers/FETCH_CONTAINERS_REJECTED';

export const FETCH_CONTAINER_PENDING = 'containers/FETCH_CONTAINER_PENDING';
export const FETCH_CONTAINER_FULFILLED = 'containers/FETCH_CONTAINER_FULFILLED';
export const FETCH_CONTAINER_REJECTED = 'containers/FETCH_CONTAINER_REJECTED';

export const CREATE_CONTAINER_PENDING = 'containers/CREATE_CONTAINER_PENDING';
export const CREATE_CONTAINER_FULFILLED = 'containers/CREATE_CONTAINER_FULFILLED';
export const CREATE_CONTAINER_REJECTED = 'containers/CREATE_CONTAINER_REJECTED';

export const UPDATE_CONTAINER_PENDING = 'containers/UPDATE_CONTAINER_PENDING';
export const UPDATE_CONTAINER_FULFILLED = 'containers/UPDATE_CONTAINER_FULFILLED';
export const UPDATE_CONTAINER_REJECTED = 'containers/UPDATE_CONTAINER_REJECTED';

export const DELETE_CONTAINER_PENDING = 'containers/DELETE_CONTAINER_PENDING';
export const DELETE_CONTAINER_FULFILLED = 'containers/DELETE_CONTAINER_FULFILLED';
export const DELETE_CONTAINER_REJECTED = 'containers/DELETE_CONTAINER_REJECTED';

export const CONTAINER_UNLOADED = 'containers/CONTAINER_UNLOADED';
export const CONTAINERS_UNLOADED = 'containers/CONTAINERS_UNLOADED';

export const SCALE_CONTAINER_PENDING = 'containers/SCALE_CONTAINER_PENDING';
export const SCALE_CONTAINER_FULFILLED = 'containers/SCALE_CONTAINER_FULFILLED';
export const SCALE_CONTAINER_REJECTED = 'containers/SCALE_CONTAINER_REJECTED';

export const MIGRATE_CONTAINER_PENDING = 'containers/MIGRATE_CONTAINER_PENDING';
export const MIGRATE_CONTAINER_FULFILLED = 'containers/MIGRATE_CONTAINER_FULFILLED';
export const MIGRATE_CONTAINER_REJECTED = 'containers/MIGRATE_CONTAINER_REJECTED';
