import { PREFIX } from '../../constants';

export const SELECTED_PROVIDER = 'containers/SELECTED_PROVIDER';

// For initializing the container create ui state
export const INIT_CONTAINERCREATE_REQUEST = `${PREFIX}INIT_CONTAINERCREATE_REQUEST`;
export const INIT_CONTAINERCREATE_FULFILLED = `${PREFIX}INIT_CONTAINERCREATE_FULFILLED`;
export const INIT_CONTAINERCREATE_REJECTED = `${PREFIX}INIT_CONTAINERCREATE_REJECTED`;
export const INIT_CONTAINERCREATE_CANCELLED = `${PREFIX}INIT_CONTAINERCREATE_CANCELLED`;

// For initializing the container edit ui state
export const INIT_CONTAINEREDIT_REQUEST = `${PREFIX}INIT_CONTAINEREDIT_REQUEST`;
export const INIT_CONTAINEREDIT_FULFILLED = `${PREFIX}INIT_CONTAINEREDIT_FULFILLED`;
export const INIT_CONTAINEREDIT_REJECTED = `${PREFIX}INIT_CONTAINEREDIT_REJECTED`;
export const INIT_CONTAINEREDIT_CANCELLED = `${PREFIX}INIT_CONTAINEREDIT_CANCELLED`;

/**
 * Containers
 */
export const FETCH_CONTAINERS_REQUEST = `${PREFIX}FETCH_CONTAINERS_REQUEST`;
export const FETCH_CONTAINERS_FULFILLED = `${PREFIX}FETCH_CONTAINERS_FULFILLED`;
export const FETCH_CONTAINERS_REJECTED = `${PREFIX}FETCH_CONTAINERS_REJECTED`;
export const FETCH_CONTAINERS_CANCELLED = `${PREFIX}FETCH_CONTAINERS_CANCELLED`;

export const FETCH_CONTAINER_REQUEST = `${PREFIX}FETCH_CONTAINER_REQUEST`;
export const FETCH_CONTAINER_FULFILLED = `${PREFIX}FETCH_CONTAINER_FULFILLED`;
export const FETCH_CONTAINER_REJECTED = `${PREFIX}FETCH_CONTAINER_REJECTED`;
export const FETCH_CONTAINER_CANCELLED = `${PREFIX}FETCH_CONTAINER_CANCELLED`;

export const CREATE_CONTAINER_REQUEST = `${PREFIX}CREATE_CONTAINER_REQUEST`;
export const CREATE_CONTAINER_FULFILLED = `${PREFIX}CREATE_CONTAINER_FULFILLED`;
export const CREATE_CONTAINER_REJECTED = `${PREFIX}CREATE_CONTAINER_REJECTED`;

export const UPDATE_CONTAINER_REQUEST = `${PREFIX}UPDATE_CONTAINER_REQUEST`;
export const UPDATE_CONTAINER_FULFILLED = `${PREFIX}UPDATE_CONTAINER_FULFILLED`;
export const UPDATE_CONTAINER_REJECTED = `${PREFIX}UPDATE_CONTAINER_REJECTED`;

export const DELETE_CONTAINER_REQUEST = `${PREFIX}DELETE_CONTAINER_REQUEST`;
export const DELETE_CONTAINER_FULFILLED = `${PREFIX}DELETE_CONTAINER_FULFILLED`;
export const DELETE_CONTAINER_REJECTED = `${PREFIX}DELETE_CONTAINER_REJECTED`;

export const SCALE_CONTAINER_REQUEST = `${PREFIX}SCALE_CONTAINER_REQUEST`;
export const SCALE_CONTAINER_FULFILLED = `${PREFIX}SCALE_CONTAINER_FULFILLED`;
export const SCALE_CONTAINER_REJECTED = `${PREFIX}SCALE_CONTAINER_REJECTED`;

export const MIGRATE_CONTAINER_REQUEST = `${PREFIX}MIGRATE_CONTAINER_REQUEST`;
export const MIGRATE_CONTAINER_FULFILLED = `${PREFIX}MIGRATE_CONTAINER_FULFILLED`;
export const MIGRATE_CONTAINER_REJECTED = `${PREFIX}MIGRATE_CONTAINER_REJECTED`;

export const PROMOTE_CONTAINER_REQUEST = `${PREFIX}PROMOTE_CONTAINER_REQUEST`;
export const PROMOTE_CONTAINER_FULFILLED = `${PREFIX}PROMOTE_CONTAINER_FULFILLED`;
export const PROMOTE_CONTAINER_REJECTED = `${PREFIX}PROMOTE_CONTAINER_REJECTED`;

export const UNLOAD_CONTAINER = `${PREFIX}UNLOAD_CONTAINER`;
export const UNLOAD_CONTAINERS = `${PREFIX}UNLOAD_CONTAINERS`;
