export const PREFIX = 'metaResource/';

export const SELECTED_PROVIDER = 'containers/SELECTED_PROVIDER';
export const UNLOAD_SELECTED_PROVIDER = 'containers/UNLOAD_SELECTED_PROVIDER';

/**
 * Containers
 */
export const FETCH_CONTAINERS_REQUEST = `${PREFIX}FETCH_CONTAINERS_REQUEST`;
export const FETCH_CONTAINERS_FULFILLED = `${PREFIX}FETCH_CONTAINERS_FULFILLED`;
export const FETCH_CONTAINERS_REJECTED = `${PREFIX}FETCH_CONTAINERS_REJECTED`;
export const FETCH_CONTAINERS_CANCELLED = `${PREFIX}FETCH_CONTAINERS_CANCELLED`;

export const FETCH_CONTAINER_REQUEST = `${PREFIX}FETCH_CONTAINER_REQUEST`;
export const FETCH_CONTAINER_FULFILLED = `${PREFIX}FETCH_CONTAINER_FULFILLED`;
export const FETCH_CONTAINER_REJECTED = `${PREFIX}FETCH_CONTAINER_REJECTED`;
export const FETCH_CONTAINER_CANCELLED = `${PREFIX}FETCH_CONTAINER_CANCELLED`;

export const FETCH_PROVIDERCONTAINER_REQUEST = `${PREFIX}FETCH_PROVIDERCONTAINER_REQUEST`;
export const CREATE_CONTAINER_REQUEST = `${PREFIX}CREATE_CONTAINER_REQUEST`;
export const CREATE_CONTAINER_FULFILLED = `${PREFIX}CREATE_CONTAINER_FULFILLED`;
export const CREATE_CONTAINER_REJECTED = `${PREFIX}CREATE_CONTAINER_REJECTED`;

export const UPDATE_CONTAINER_REQUEST = `${PREFIX}UPDATE_CONTAINER_REQUEST`;
export const UPDATE_CONTAINER_FULFILLED = `${PREFIX}UPDATE_CONTAINER_FULFILLED`;
export const UPDATE_CONTAINER_REJECTED = `${PREFIX}UPDATE_CONTAINER_REJECTED`;

export const DELETE_CONTAINER_REQUEST = `${PREFIX}DELETE_CONTAINER_REQUEST`;
export const DELETE_CONTAINER_FULFILLED = `${PREFIX}DELETE_CONTAINER_FULFILLED`;
export const DELETE_CONTAINER_REJECTED = `${PREFIX}DELETE_CONTAINER_REJECTED`;

export const SCALE_CONTAINER_REQUEST = `${PREFIX}SCALE_CONTAINER_REQUEST`;
export const SCALE_CONTAINER_FULFILLED = `${PREFIX}SCALE_CONTAINER_FULFILLED`;
export const SCALE_CONTAINER_REJECTED = `${PREFIX}SCALE_CONTAINER_REJECTED`;

export const MIGRATE_CONTAINER_REQUEST = `${PREFIX}MIGRATE_CONTAINER_REQUEST`;
export const MIGRATE_CONTAINER_FULFILLED = `${PREFIX}MIGRATE_CONTAINER_FULFILLED`;
export const MIGRATE_CONTAINER_REJECTED = `${PREFIX}MIGRATE_CONTAINER_REJECTED`;

export const PROMOTE_CONTAINER_REQUEST = `${PREFIX}PROMOTE_CONTAINER_REQUEST`;
export const PROMOTE_CONTAINER_FULFILLED = `${PREFIX}PROMOTE_CONTAINER_FULFILLED`;
export const PROMOTE_CONTAINER_REJECTED = `${PREFIX}PROMOTE_CONTAINER_REJECTED`;

export const FETCH_CONTAINERS_DROPDOWN_REQUEST = `${PREFIX}FETCH_CONTAINERS_DROPDOWN_REQUEST`;
export const FETCH_CONTAINERS_DROPDOWN_FULFILLED = `${PREFIX}FETCH_CONTAINERS_DROPDOWN_FULFILLED`;
export const FETCH_CONTAINERS_DROPDOWN_REJECTED = `${PREFIX}FETCH_CONTAINERS_DROPDOWN_REJECTED`;

export const UNLOAD_CONTAINER = `${PREFIX}UNLOAD_CONTAINER`;
export const UNLOAD_CONTAINERS = `${PREFIX}UNLOAD_CONTAINERS`;

// TODO: move
export const UNLOAD_ENVIRONMENT = `${PREFIX}UNLOAD_ENVIRONMENT`;
